<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 *
 * This package designed for Magento COMMUNITY edition
 * PSS Digital does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * PSS Digital does not provide extension support in case of * incorrect edition usage.
 *
 * @author PSS Digital Team
 * @category PSS
 * @package PSS_WordPress
 * @copyright Copyright (c) 2018 PSS (https://www.pss-ti.com)
 * @license http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */
?>
<?php $items = $this->getDateItems() ?>
<?php if ($items): ?>
	<div class="block block-blog block-blog-archives">
		<?php if ($title = $this->getTitle()): ?>
			<div class="block-title">
				<strong><?php echo __($title) ?></strong>
			</div>
		<?php endif; ?>
		<div class="block-content">
			<div id="calendar_wrap">
				<table id="wp-calendar">
					<thead>
						<tr>
							<th scope="col"><?php echo __('M') ?></th>
							<th scope="col"><?php echo __('T') ?></th>
							<th scope="col"><?php echo __('W') ?></th>
							<th scope="col"><?php echo __('T') ?></th>
							<th scope="col"><?php echo __('F') ?></th>
							<th scope="col"><?php echo __('S') ?></th>
							<th scope="col"><?php echo __('S') ?></th>
						</tr>
					</thead>
					<tfoot>
						<tr>
							<?php if ($this->hasPreviousUrl()): ?>
								<td colspan="3" class="a-left">
									<a href="<?php echo $this->getPreviousUrl() ?>">&laquo; <?php echo $this->getPreviousText() ?></a>
								</td>
							<?php else: ?>
								<td colspan="3" class="pad">&nbsp;</td>
							<?php endif; ?>
							<td class="pad">&nbsp;</td>
							<?php if ($this->hasNextUrl()): ?>
								<td colspan="3" class="a-right">
									<a href="<?php echo $this->getNextUrl() ?>"><?php echo $this->getNextText() ?> &raquo;</a>
								</td>
							<?php else: ?>
								<td colspan="3" class="pad">&nbsp;</td>
							<?php endif; ?>
						</tr>
					</tfoot>
					<tbody>
						<?php foreach($items as $it => $row): ?>
							<tr>
								<?php foreach($row as $html): ?>
									<?php if (is_null($html)): ?>
										<td class="pad">&nbsp;</td>
									<?php else: ?>
										<td><?php echo $html ?></td>
									<?php endif; ?>
								<?php endforeach; ?>
							</tr>
						<?php endforeach; ?>
					</tbody>
				</table>
			</div>
		</div>
	</div>
<?php endif; ?>