<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 *
 * This package designed for Magento COMMUNITY edition
 * PSS Digital does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * PSS Digital does not provide extension support in case of * incorrect edition usage.
 *
 * @author PSS Digital Team
 * @category PSS
 * @package PSS_WordPress
 * @copyright Copyright (c) 2018 PSS (https://www.pss-ti.com)
 * @license http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */
?>
<?php if ($tags = $this->getTags()): ?>
	<?php $tagCount = count($tags) ?>
	<div class="block block-blog block-blog-cloud">
		<?php if ($title = $this->getTitle()): ?>
			<div class="block-title">
				<strong><?php echo __($title) ?></strong>
			</div>
		<?php endif; ?>
		<div class="block-content">
			<ul class="tags-list">
				<?php foreach ($tags as $tag): ?>
					<li<?php if (--$tagCount < 1): ?> class="last"<?php endif; ?>><a href="<?php echo $tag->getUrl() ?>" style="font-size:<?php echo $this->getFontSize($tag) ?>%;"><?php echo $this->escapeHtml($tag->getName()) ?></a></li>
				<?php endforeach; ?>
			</ul>
		</div>
	</div>
<?php endif; ?>