<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 *
 * This package designed for Magento COMMUNITY edition
 * PSS Digital does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * PSS Digital does not provide extension support in case of * incorrect edition usage.
 *
 * @author PSS Digital Team
 * @category PSS
 * @package PSS_WordPress
 * @copyright Copyright (c) 2018 PSS (https://www.pss-ti.com)
 * @license http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */
?>
<?php if ($image = $this->getImage()): ?>
	<div class="block block-blog block-image">
		<?php if ($title = $this->getTitle()): ?>
			<div class="block-title">
				<strong><?php echo __($title) ?></strong>
			</div>
		<?php endif; ?>
		<div class="block-content">
			<a href="<?php echo $this->getLink() ?>"<?php if ($this->getLinktarget()): ?> target="<?php echo $this->getLinktarget() ?>"<?php endif; ?>>
				<img src="<?php echo $this->getImageUrl() ?>" alt="<?php echo $this->getAlt() ?>" style="max-width: 100%;" />
			</a>
			<?php if ($this->getDescription()): ?>
				<p><?php echo $this->getDescription() ?></p>
			<?php endif; ?>
		</div>
	</div>
<?php endif; ?>