<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 *
 * This package designed for Magento COMMUNITY edition
 * PSS Digital does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * PSS Digital does not provide extension support in case of * incorrect edition usage.
 *
 * @author PSS Digital Team
 * @category PSS
 * @package PSS_WordPress
 * @copyright Copyright (c) 2018 PSS (https://www.pss-ti.com)
 * @license http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */
?>
<div class="block block-blog block-blog-meta">
	<div class="block-title">
		<strong><span><?php echo __($this->getTitle()) ?></span></strong>
	</div>
	<div class="block-content">
		<ul id="wp-meta-list">
			<li class="item">
				<a href="http://wordpress.org/" title="<?php echo __('Powered by WordPress, state-of-the-art semantic personal publishing platform.') ?>"><span><?php echo __('WordPress.org') ?></span></a>
			</li>
			<li class="item">
				<a href="http://www.magentocommerce.com/" title="<?php echo __('Magento eCommerce') ?>"><span><?php echo __('Magento') ?></span></a>
			</li>
		</ul>
	</div>
</div>