<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 *
 * This package designed for Magento COMMUNITY edition
 * PSS Digital does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * PSS Digital does not provide extension support in case of * incorrect edition usage.
 *
 * @author PSS Digital Team
 * @category PSS
 * @package PSS_WordPress
 * @copyright Copyright (c) 2018 PSS (https://www.pss-ti.com)
 * @license http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */
?>
<?php $items = $this->getFeedItems() ?>
<?php if (count($items) > 0): ?>
	<div class="block block-blog block-rss">
		<?php if ($title = $this->getTitle()): ?>
			<div class="block-title">
				<strong><span><?php echo $this->__($title) ?></span></strong>
			</div>
		<?php endif; ?>
		<div class="block-content">
			<ul id="<?php echo $this->getListId() ?>">
			<?php foreach($items as $item): ?>
				<li class="item">
					<a href="<?php echo $item->getLink() ?>" title="<?php echo $this->htmlEscape($item->getTitle()) ?>">
						<?php echo $this->htmlEscape($item->getTitle()) ?>
					</a>
					<?php if ($this->getShowDate()): ?>
						<div class="rss-date"><?php echo $this->helper('wordpress')->formatDate($item->getData('pubDate')) ?></div>
					<?php endif; ?>
					<?php if ($this->getShowSummary()): ?>
						<div class="rss-description"><?php echo $this->__('%s [...]', $item->getDescription()) ?></div>
					<?php endif; ?>
				</li>
			<?php endforeach; ?>
			</ul>
		</div>
	</div>
<?php endif; ?>