<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 *
 * This package designed for Magento COMMUNITY edition
 * PSS Digital does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * PSS Digital does not provide extension support in case of * incorrect edition usage.
 *
 * @author PSS Digital Team
 * @category PSS
 * @package PSS_WordPress
 * @copyright Copyright (c) 2018 PSS (https://www.pss-ti.com)
 * @license http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */
?>
<?php $_helper = $this->helper('Magento\Catalog\Helper\Output') ?>
<?php $_products = $this->getProductCollection() ?>
<?php if (count($_products) > 0): ?>
	<div class="shortcode-product">
		<ol class="products">
		<?php foreach($_products as $_product): ?>
			<li>
				<a href="<?php echo $_product->getProductUrl() ?>" class="product photo product-item-photo">
					<?php echo $this->getImage($_product, 'category_page_list')->toHtml() ?>
				</a> 
				<strong class="product name product-item-name">
					<a class="product-item-link" href="<?php echo $_product->getProductUrl() ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a>
				</strong>
			</li>
		<?php endforeach; ?>
		</ol>
	</div>
<?php endif; ?>