<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 *
 * This package designed for Magento COMMUNITY edition
 * PSS Digital does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * PSS Digital does not provide extension support in case of * incorrect edition usage.
 *
 * @author PSS Digital Team
 * @category PSS
 * @package PSS_WordPress
 * @copyright Copyright (c) 2018 PSS (https://www.pss-ti.com)
 * @license http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */

/**
 * @var \PSS\WordPress\Block\PostEntity $block
 */
$postList = $block->getPostList();
$titlePost = $block->getTitle();
?>
<div class="content-heading">
    <h2 class="title">
        <?= $titlePost; ?>
    </h2>
</div>
<div data-role="content">
    <div class="post-list-wrapper">
        <?php if($postList && count($postList) > 0 ): ?>
            <ol class="post-list">
                <?php foreach ($postList as $post) : ?>
                    <?php if ($renderedPostHtml = $block->renderPost($post)): ?>
                        <li class="item<?php if ($post->isSticky()): ?> featured is-sticky<?php endif; ?> <?php echo $post->getPostFormat(); ?>">
                            <?= $renderedPostHtml ?>
                        </li>
                    <?php endif; ?>
                <?php endforeach; ?>
            </ol>
        <?php else: ?>
            <?= __('There are no related Posts'); ?>
        <?php endif; ?>
    </div>
</div>