<div class="section-container section-gray section-recomendaciones">
    <div class="container">
        <div class="row no-pad">
            <div class="col-xs-12">
                <!--{{widget type="WeltPixel\OwlCarouselSlider\Block\Slider\Category" category="category/547"}}</div>-->
                <?= $block->getChildHtml('slider-category'); ?>
            </div>
        </div>
    </div>
</div>
