<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Sales\Block\Order\Email\Items\DefaultItems */

/** @var $_item \Magento\Sales\Model\Order\Item */
$_item = $block->getItem();
$_order = $_item->getOrder();
$_store = $_order->getStore();
$productName = $_item->getName();

if($_item->getProductType() == 'configurable' ) {
    $option = $_item->getProductOptions();
    $productName = $option['simple_name'];
}

$_imageHelper = \Magento\Framework\App\ObjectManager::getInstance()->get('Magento\Catalog\Helper\Image');
$_baseImageUrl = $_store->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA).'catalog/product';
?>
<tr>
    <td class="item-info<?php if ($block->getItemOptions()): ?> has-extra<?php endif; ?>" style="position: relative; font-family: 'Trebuchet MS', 'Open Sans', 'sans-serif';">
        <img src="<?= $_imageHelper->init($_item->getProduct(), 'small_image', ['type'=>'small_image'])->keepAspectRatio(true)->resize('65','65')->getUrl();?>" alt="<?= __('Product Image');?>" style="display: inline-block">
        <div class="custom-info" style="display: inline-block; max-width: 530px; vertical-align: top;">
            <p class="product-name"><?= $block->escapeHtml($productName) ?></p>
            <p class="sku"><?= /* @escapeNotVerified */  __('SKU') ?>: <?= $block->escapeHtml($block->getSku($_item)) ?></p>
        </div>
        <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addInfoBlock) :?>
            <?= $addInfoBlock->setItem($_item)->toHtml() ?>
        <?php endif; ?>
        <?= $block->escapeHtml($_item->getDescription()) ?>
    </td>
    <td class="item-qty" style="font-family: 'Trebuchet MS', 'Open Sans', 'sans-serif';"><?= /* @escapeNotVerified */  $_item->getQtyOrdered() * 1 ?></td>
    <td class="item-price" style="font-family: 'Trebuchet MS', 'Open Sans', 'sans-serif';">
        <?= /* @escapeNotVerified */  $block->getItemPrice($_item) ?>
        <?php if($_item->getIsGift()){ ?>
            <div class="custom-gift" style="bottom: 10px; position: absolute; right: -176px;">
                <img src='<?php echo $this->getViewFileUrl('images/icon-gift-cart-red.png'); ?>' alt="Gift" style="display: inline-block; height: 29px; width: 29px; vertical-align: middle;">
                <p class="contain-gift" style="display: inline-block; padding-left: 5px; vertical-align: middle;color: #d92e14;font-family: 'Trebuchet MS', 'Open Sans', 'sans-serif';"><?= /* @escapeNotVerified */  __('Es para Regalo') ?></p>
            </div>
        <?php } ?>
    </td>
</tr>
<?php if ($_item->getGiftMessageId() && $_giftMessage = $this->helper('Magento\GiftMessage\Helper\Message')->getGiftMessage($_item->getGiftMessageId())): ?>
<tr>
    <td colspan="3" class="item-extra" style="font-family: 'Trebuchet MS', 'Open Sans', 'sans-serif';">
        <table class="message-gift">
            <tr>
                <td>
                    <h3><?= /* @escapeNotVerified */  __('Gift Message') ?></h3>
                    <strong><?= /* @escapeNotVerified */  __('From:') ?></strong> <?= $block->escapeHtml($_giftMessage->getSender()) ?>
                    <br /><strong><?= /* @escapeNotVerified */  __('To:') ?></strong> <?= $block->escapeHtml($_giftMessage->getRecipient()) ?>
                    <br /><strong><?= /* @escapeNotVerified */  __('Message:') ?></strong>
                    <br /><?= $block->escapeHtml($_giftMessage->getMessage()) ?>
                </td>
            </tr>
        </table>
    </td>
</tr>
<?php endif; ?>
