<?php
/**
 * @author Israel Yasis
 */

// @codingStandardsIgnoreFile

/** @var \Alfa9\Customer\Block\Widget\Taxvat $block */
?>
<div class="field taxvat<?php if ($block->isRequired()) echo ' required'; ?>">
    <label class="label" for="<?= $block->escapeHtmlAttr($block->getFieldId('taxvat')) ?>"><span><?= $block->escapeHtml(__('Tax/VAT number')) ?></span></label>
    <div class="control">
        <input type="text" id="<?= $block->escapeHtmlAttr($block->getFieldId('taxvat')) ?>" name="<?= $block->escapeHtmlAttr($block->getFieldName('taxvat')) ?>"
               value="<?= $block->escapeHtmlAttr($block->getTaxvat()) ?>" title="<?= $block->escapeHtmlAttr(__('Tax/VAT number')) ?>"
               class="input-text <?= $block->escapeHtmlAttr($this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('taxvat')) ?>"
            <?php if ($block->isRequired()) echo ' data-validate ="{required:true, \'validate-nif-nie\': true}"' ?>>
    </div>
</div>
