<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 *
 * This package designed for Magento COMMUNITY edition
 * PSS Digital does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * PSS Digital does not provide extension support in case of * incorrect edition usage.
 *
 * @author PSS Digital Team
 * @category PSS
 * @package PSS_WordPress
 * @copyright Copyright (c) 2018 PSS (https://www.pss-ti.com)
 * @license http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */
/**
 * @var \PSS\WordPress\Model\Post $post
 */
?>
<?php if ($post = $this->getPost()): ?>
	<?php if ($categoryString = $post->getTermCollectionAsString('category')): ?>
		<div class="post-categories post-meta-item"><strong><?php echo __('Categories') ?>:</strong> <?php echo $categoryString ?></div>
	<?php endif; ?>
<?php endif; ?>