<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 *
 * This package designed for Magento COMMUNITY edition
 * PSS Digital does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * PSS Digital does not provide extension support in case of * incorrect edition usage.
 *
 * @author PSS Digital Team
 * @category PSS
 * @package PSS_WordPress
 * @copyright Copyright (c) 2018 PSS (https://www.pss-ti.com)
 * @license http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */
?>
<?php if ($post = $this->getPost()): ?>
	<?php if ((int)$this->getHeadingLevel() === 1): ?>
		<h1 class="post-name"><?php echo $this->escapeHtml($post->getName()) ?></h1>
	<?php else: ?>
		<h<?php echo $this->getHeadingLevel() ?> class="post-name">
			<a href="<?php echo $post->getUrl() ?>" title="<?php echo $this->escapeHtml($post->getName()) ?>">
				<?php echo $this->escapeHtml($post->getName()) ?>
			</a>
		</h<?php echo $this->getHeadingLevel() ?>>
	<?php endif; ?>
<?php endif; ?>