<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 *
 * This package designed for Magento COMMUNITY edition
 * PSS Digital does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * PSS Digital does not provide extension support in case of * incorrect edition usage.
 *
 * @author PSS Digital Team
 * @category PSS
 * @package PSS_WordPress
 * @copyright Copyright (c) 2018 PSS (https://www.pss-ti.com)
 * @license http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */

/**
 * @var \PSS\WordPress\Block\Post\View\RelatedProducts $block
 */
$products = $block->getProductsRelated();
$imageType = 'product_small_image';
?>
<?php if(false): ?>
<div class="related-posts-section">
    <div class="box-title" onclick="openProducts()">
        <h2 class="related-posts-section-title">
            <?php echo __('Related Products');  ?>
            <i class="fa fa-plus"></i>
        </h2>
    </div>
    <div class="box-content products wrapper grid products-grid" id="post-products" style="display: none">
        <?php if($products && count($products) > 0): ?>
            <ul class="products list items product-items">
                <?php
                /** @var \Magento\Catalog\Model\Product $product */
                foreach ($products as $product): ?>
                    <?php $image = $block->getImage($product, $imageType); ?>
                    <li class="item product product-item">
                        <img src="<?php echo  $image->getImageUrl(); ?>"/>
                        <h5>
                            <a href="<?php echo $product->getProductUrl(); ?>"><?php echo $product->getName(); ?></a>
                        </h5>
                    </li>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>
    </div>
</div>
<script>
    require([
        'jquery'
    ], function (jQuery) {
        function openProducts(){
            var postProducts = jQuery('.related-posts-section #post-products');
            if (postProducts.length > 0) {
                if(postProducts.is(':visible')) {
                    postProducts.hide();
                } else {
                    postProducts.show();
                }
            }
        }
        window.openProducts = openProducts;
    });
</script>
<?php endif; ?>