<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 *
 * This package designed for Magento COMMUNITY edition
 * PSS Digital does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * PSS Digital does not provide extension support in case of * incorrect edition usage.
 *
 * @author PSS Digital Team
 * @category PSS
 * @package PSS_WordPress
 * @copyright Copyright (c) 2018 PSS (https://www.pss-ti.com)
 * @license http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */
?>
<?php
/*
 * If you are using custom post types, you can create a custom render for the post type easily
 * Simply create a file using the name of the custom post type in this folder (in your custom theme)
 * For example, if your custom post type is 'news_article', you would create a file named news_article.phtml
 * This file would live in the templates/post/list/renderer/news_article.phtml in your custom theme
 */
?>