<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var $block \Magento\Theme\Block\Html\Title
 */
$cssClass = $block->getCssClass() ? ' ' . $block->getCssClass() : '';
$title = '';
if (trim($block->getPageHeading())) {
    $title = '<span class="base" data-ui-id="page-title-wrapper" ' .  $block->getAddBaseAttribute() . '>'
        . $block->escapeHtml($block->getPageHeading()) . '</span>';
}
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$requestInterface = $objectManager->get('Magento\Framework\App\RequestInterface');
$fullactionName = $requestInterface->getFullActionName();
if($fullactionName == "catalog_product_view"){
    $product = $objectManager->get('Magento\Framework\Registry')->registry('current_product');
    $title = $product->getName();
    $optionId = $product->getManufacturer();
    $brand_name = "";
    if($optionId){
        $attr = $product->getResource()->getAttribute('manufacturer');
        if ($attr->usesSource()) {
           $brand_name = $attr->getSource()->getOptionText($optionId);
           $brand_name = str_replace("&#039;","'",$brand_name);
        }
    }
    if($brand_name){ 
        $title = str_ireplace($brand_name,"",$title);
    }
}
?>
<?php if ($title): ?>
<div class="page-title-wrapper<?= /* @escapeNotVerified */ $cssClass ?>">
    <h1 class="page-title"
        <?php if ($block->getId()): ?> id="<?= /* @escapeNotVerified */ $block->getId() ?>" <?php endif; ?>
        <?php if ($block->getAddBaseAttributeAria()): ?>
            aria-labelledby="<?= /* @escapeNotVerified */ $block->getAddBaseAttributeAria() ?>"
        <?php endif; ?>>
        <?= /* @escapeNotVerified */ $title ?>
    </h1>
    <?= $block->getChildHtml() ?>
</div>
<?php endif; ?>
