<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php 
    $productName = $_product->getName();
    $optionId = $_product->getManufacturer(); 
    $brand_name = "";
    
    if($optionId){
        $attr = $_product->getResource()->getAttribute('manufacturer');
        if ($attr->usesSource()) {
           $brand_name = $attr->getSource()->getOptionText($optionId);
           $brand_name = str_replace("&#039;","'",$brand_name);
        }
    }
    if($brand_name){ 
        $productName = str_ireplace($brand_name,"",$productName);
    }
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    /** @var \Magento\CatalogInventory\Model\Configuration $catalogInventoryConfig */
    $catalogInventoryConfig = $objectManager->get('Magento\CatalogInventory\Model\Configuration');
?>
<?php $buttonTitle = __('Add to Cart'); ?>
<div class="product-details-information" id="product-details-information-form"></div>
<?php if ($_product->isSaleable()): ?>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()): ?>
        <div class="field qty">
            <label class="label" for="qty"><span><?= /* @escapeNotVerified */ __('Qty') ?></span></label>
            <div class="control">
                <?php if($catalogInventoryConfig->getMaxSaleQty() > 1): ?>
                    <input type="button" id="qty-less" value="-" class="qty-action qty-less" />
                <?php endif; ?>
                <input type="number"
                       name="qty"
                       id="qty"
                       value="<?= /* @escapeNotVerified */ $block->getProductDefaultQty() * 1 ?>"
                       title="<?= /* @escapeNotVerified */ __('Qty') ?>"
                       class="input-text qty"
                       data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                       />
                <?php if($catalogInventoryConfig->getMaxSaleQty() > 1): ?>
                    <input type="button" id="qty-plus" value="+" class="qty-action qty-plus" />
                <?php endif; ?>
            </div>
        </div>
        <?php endif; ?>
        <div class="actions">
            <input type="hidden" name="customproductname" value="<?php echo trim($productName); ?>" />
            <button type="submit"
                    title="<?= /* @escapeNotVerified */ $buttonTitle ?>"
                    class="action primary tocart"
                    id="product-addtocart-button">
                <span><?= /* @escapeNotVerified */ $buttonTitle ?></span>
            </button>
            <?= $block->getChildHtml('', true) ?>
        </div>
    </div>
</div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>
