<?php
use Magento\Framework\App\Action\Action;
// @codingStandardsIgnoreFile
?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
?>
<?php
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $brand_helper = $objectManager->get('\Mageplaza\Shopbybrand\Helper\Data');
    $tax_helper   = $objectManager->get('\Magento\Catalog\Helper\Data');
    $storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
 ?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?= /* @escapeNotVerified */ __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?= /* @escapeNotVerified */ $viewMode ?> products-<?= /* @escapeNotVerified */ $viewMode ?>">
        <?php $iterator = 1; ?>
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
                <?= /* @escapeNotVerified */ ($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                <div class="product-item-info" data-container="product-grid">
                    <?php
                    $productImage = $block->getImage($_product, $image);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php // Discount Label ?>
                    <?php
                        $visible = '';
                        $discountPvp = 0;
                        $configdiscountPvp = [];
                        if($_product->getTypeId() == \Magento\ConfigurableProduct\Model\Product\Type\Configurable::TYPE_CODE){
                            $productTypeInstance = $_product->getTypeInstance();
                            $usedProducts = $productTypeInstance->getUsedProducts($_product);
                            foreach ($usedProducts  as $child) {
                                $child = $objectManager->get('Magento\Catalog\Model\Product')->load($child->getId());
                                $finalPrice = $tax_helper->getTaxPrice($child, $child->getFinalPrice(), true);
                                $finalPrice = round($finalPrice, 2);
                                $pvpPrice = $child->getResource()->getAttributeRawValue($child->getId(),'pvp',$storeManager->getStore()->getStoreId());
                                if($pvpPrice && $pvpPrice > 0 && $pvpPrice > $finalPrice) {
                                    $visible = 'visible';
                                    $pvpPrice = round($pvpPrice, 2);
                                    $savePercent = (1 - ($finalPrice / $pvpPrice)) * 100;
                                    $configdiscountPvp[] = round($savePercent, 0);
                                }
                            }
                            if(!empty($configdiscountPvp)){
                                $discountPvp = max($configdiscountPvp);
                            }
                        }else{
                            $priceInfo = $_product->getPriceInfo();
                            $finalPrice = $priceInfo->getPrice('final_price')->getAmount()->getValue();
                            $pvpPrice = $_product->getData('pvp');
                            $discountPvp = 0;
                        
                            if($pvpPrice && $pvpPrice > 0 && $pvpPrice > $finalPrice) {
                                $visible = 'visible';
                                $pvpPrice = round($pvpPrice, 2);
                                $savePercent = (1 - ($finalPrice / $pvpPrice)) * 100;
                                $discountPvp = round($savePercent, 0);
                            }
                        }
                        
                        
                        if(!$discountPvp){
                            $visible = '';
                        }
                    ?>
                    <?php if($discountPvp): ?>
                        <div class="product pvp_discount <?= /* @escapeNotVerified */ $visible; ?>">
                            <?php if( $_product->getTypeId() != 'simple' ): ?>
                                <div class="pvp_discount_label"><?php echo __('Hasta'); ?></div>
                            <?php endif; ?>
                            <div class="discountPvp">-<?= /* @escapeNotVerified */  $discountPvp; ?>%</div>
                        </div>
                    <?php endif; ?>
                    <?php // Product Image ?>
                    <div class="product-image">
                        <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                            <?= $productImage->toHtml() ?>
                        </a>
                        <div data-role="add-to-links" class="wishlist-product-grid actions-secondary"<?= strpos($pos, $viewMode . '-secondary') ? $position : '' ?>>
                            <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                            <?php endif; ?>
                        </div>
                    </div>
                    <div class="product details product-item-details">
                        <?php
                        $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <div class="product-title-wrapper">
                            <?php $brand_name = $_product->getResource()->getAttribute('manufacturer')->getFrontend()->getValue($_product); ?>
                            <?php $brand_url = $brand_helper->getCustomBrandUrl($brand_name); ?>
                            <?php $brand_name = str_replace("&#039;","'",$brand_name); ?>
                            <h2 class="product-item-manufacturer">
                                <a class="product-item-link"
                                   href="<?= /* @escapeNotVerified */ $brand_url ?>">
                                    <?= /* @escapeNotVerified */ $_product->getResource()->getAttribute('manufacturer')->getFrontend()->getValue($_product); ?>
                                </a>
                            </h2>
                            <?php 
                                $productName = $_product->getName();
                                if($brand_name){
                                    $productName = str_ireplace($brand_name,"",$productName);
                                }
                            ?>
                            <?php
                            $product = $objectManager->create('Magento\Catalog\Model\Product')->load($_product->getId());
                            ?>
                            <?php $gama = $product->getData('gama'); ?>
                            
                            <?php if($gama){ ?>
                            <div class="product gama-attribute product-gama-attr-val">
                                <a class="product-item-link"
                                   href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>">
                                    <?= /* @escapeNotVerified */ $gama ?>
                                </a>
                            </div>
                            <?php } ?>
                            <?php if(false): ?>
                            <strong class="product name product-item-name">
                                <a class="product-item-link" href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>">
                                    <?= /* @escapeNotVerified */$productName ?>
                                </a>
                            </strong>
                            <?php endif; ?>
                            <?php if ($showDescription):?>
                            <?php if($attributeVolume = $product->getResource()->getAttribute('volumen')): ?>
                               <?php $volumen = $attributeVolume->getFrontend()->getValue($product); ?>
                                    <div class="product description product-item-description">
                                        <span class="product_short_description"><?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?><?php if($volumen){ echo '<span class="product_volume"> '.$volumen.'</span>'; } ?></span>
                                    </div>
                                <?php endif; ?>
                            <?php endif; ?>

                        </div>

                        <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>

                        <div class="product-price-wrapper">
                            <?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?>
                            <?php if ($_product->getData('express_stock') > 0):?>
                                <strong class="product-item-entrega"><?php echo __('Express Delivery') ?></strong>
                            <?php endif;?>
                        </div>

                        <?= $block->getProductDetailsHtml($_product) ?>

                        <div class="product-item-inner">
                            <div class="product actions product-item-actions"<?= strpos($pos, $viewMode . '-actions') ? $position : '' ?>>
                                <div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $position : '' ?>>
                                    <?php if ($_product->isSaleable()): ?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <form data-role="tocart-form" data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>" action="<?= /* @NoEscape */ $postParams['action'] ?>" method="post">
                                            <input type="hidden" name="product" value="<?= /* @escapeNotVerified */ $postParams['data']['product'] ?>">
                                            <input type="hidden" name="<?= /* @escapeNotVerified */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @escapeNotVerified */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                            <?= $block->getBlockHtml('formkey') ?>
                                            <button type="submit"
                                                    title="<?= $block->escapeHtml(__('Buy')) ?>"
                                                    class="action tocart primary">
                                                <span><?= /* @escapeNotVerified */ __('Buy') ?></span>
                                            </button>
                                        </form>
                                    <?php else: ?>
                                        <?php if ($_product->isAvailable()): ?>
                                            <div class="stock available"><span><?= /* @escapeNotVerified */ __('In stock') ?></span></div>
                                        <?php else: ?>
                                            <div class="stock unavailable"><span><?= /* @escapeNotVerified */ __('Out of stock') ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <?php unset($configdiscountPvp);  ?>
                <?= ($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
            <?php endforeach; ?>
        </ol>
        <script type="text/javascript">
            require(['jquery'],function($){
                $(document).ready(function(){
                    setTimeout(function(){
                        if(jQuery(".amasty-label-container").length > 0){
                            $(".amasty-label-container").parents(".product-item").addClass('label-exist');
                            $(".product-item.label-exist").children().addClass('label-exist');
                        }
                    }, 2000);
                });
            });
        </script>
    </div>
    <?= $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= /* @NoEscape */ $_product->getSku() ?>"
                }
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
