<!-- weltpixel_pre-footer -->
<div class="container footer-top">
    <div class="row">
        <div class="col-xs-4">
            <div class="social">
                <span>Síguenos en</span>
                <div class="icon">
                    <a href="#"><i class="fa fa-facebook fa-2x"></i></a>
                    <a href="#"><i class="fa fa-twitter fa-2x"></i></a>
                    <a href="#"><i class="fa fa-instagram fa-2x"></i></a>
                    <a href="#"><i class="fa fa-google-plus fa-2x"></i></a>
                </div>
            </div>
        </div>
        <div class="col-xs-4">
            <span>900 866 634 </span>
            <p>
                Atención al cliente 
                Horario de atención: 
                Lunes / vierns de 10:00 a 20h30 
                Sábados de 10:00 a 19:00
            </p>
        </div>
        <div class="col-xs-4">
            <span>¿Quieres estar al día?</span>
            <span>Recibe en exlusiva todas nuestaras ofertas y novedades</span>
            <div class="subs-form">
            </div>
        </div>
    </div>
</div>

<!-- weltpixel_footer_v1 -->
<div class="container footer-down">
    <div class="row">
        <div class="col-xs-4">
            <div class="row">
                <div class="col-xs-6">
                    <img class="logo" src=""/>
                </div>
                <div class="col-xs-6">
                    <label>Acerca de </label>
                    <ul>
                        <li><a href="#">Historia</a></li>
                        <li><a href="#">Trabajo</a></li>
                        <li><a href="#">Blog</a></li>
                        <li><a href="#">Blog</a></li>
                        <li><a href="#">Nuestras tiendas</a></li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="col-xs-5">
            <div class="row">
                <div class="col-xs-6 service">
                    <label>Servicio</label>
                    <ul>
                        <li><a href="#">Contacto</a></li>
                        <li><a href="#">Informació de envío</a></li>
                        <li><a href="#">Política de devoluciones</a></li>
                        <li><a href="#">Terminos y condiciones</a></li>
                        <li><a href="#">Política de privacidad</a></li>
                        <li><a href="#">Política de Coockies</a></li>
                    </ul>
                </div>
                <div class="col-xs-6 client-service">
                    <label>Servicio al Cliente</label>
                    <ul>
                        <li><a href="#">Lista de stocks</a></li>
                        <li><a href="#">Recoje y reserva</a></li>
                        <li><a href="#">FAQ</a></li>
                        <li><a href="#">Tarjeta regalo</a></li>
                        <li><a href="#">Búsquedas más populares</a></li>
                        <li><a href="#">Nuestras marcas</a></li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="col-xs-3">
            <div class="payment-logos">
                <i class="fa fa-cc-visa fa-2x"></i>
                <i class="fa fa-cc-mastercard fa-2x"></i>
                <i class="fa fa-paypal fa-2x"></i>
            </div>
            <div class="cp">
                <span>
                    2018 San Remo Perfumeries,  C/Ávila 121, 08018 Barcelona
                </span>
            </div>
        </div>
    </div>
</div>