<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 *
 * This package designed for Magento COMMUNITY edition
 * PSS Digital does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * PSS Digital does not provide extension support in case of * incorrect edition usage.
 *
 * @author PSS Digital Team
 * @category PSS
 * @package PSS_WordPress
 * @copyright Copyright (c) 2018 PSS (https://www.pss-ti.com)
 * @license http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */
?>
<?php if ($text = $this->getIntroText()): ?>
	<p class="post-list-description"><?php echo $text ?></p>
<?php endif; ?>
<?php if ($postList = trim($this->getPostListHtml())): ?>
	<?php echo $postList ?>
<?php else: ?>
	<p class="note-msg"><?php echo __('There are no posts matching your selection.') ?>
<?php endif; ?>