<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 *
 * This package designed for Magento COMMUNITY edition
 * PSS Digital does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * PSS Digital does not provide extension support in case of * incorrect edition usage.
 *
 * @author PSS Digital Team
 * @category PSS
 * @package PSS_WordPress
 * @copyright Copyright (c) 2018 PSS (https://www.pss-ti.com)
 * @license http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */
?>
<?php $post = $this->getPost() ?>
<?php $comments = $this->getComments() ?>
<div id="comments" class="comments-wrapper">
	<?php if (count($comments) > 0): ?>
		<?php if ($this->getCommentCount() == 1): ?>
			<h2><?php echo __('1 Comment') ?></h2>
		<?php else: ?>
			<h2><?php echo __('%1 Comments', $this->getCommentCount()) ?></h2>
		<?php endif; ?>
		<?php echo $this->getCommentsHtml() ?>
		<?php echo $this->getPagerHtml() ?>
	<?php endif; ?>
	<?php echo $this->getFormHtml() ?>
</div>
