
<?php /* @var  \PSS\ProductAlert\Block\Product\View $block */

?>
<div class="product alert <?= $block->getHtmlClass() ?>">
    <form id="edit_form" method="post"
          data-mage-init='{"validation": {"errorClass": "mage-error"}}'
          action="<?= /* @escapeNotVerified */ $block->getPostAction(); ?>">
        <input type="hidden" name="product_id" value="<?= $block->getProductId(); ?>" />
        <div class="field newsletter">
            <label class="label" style="display: none;" for="newsletter"><span><?= $block->escapeHtml(__('Sign Up for the notification of new stock.')) ?></span></label>
            <div class="control">
                <input name="email" type="email" id="newsletter"
                       placeholder="<?= $block->escapeHtml(__('Ingresa tu email y te avisamos.')) ?>"
                       data-validate="{required:true, 'validate-email':true}"/>
            </div>
        </div>
        <div class="actions">
            <button class="action subscribe primary" title="<?= $block->escapeHtmlAttr(__('Submit')) ?>" type="submit">
                <span><?= $block->escapeHtml(__('Submit')) ?></span>
            </button>
        </div>
    </form>
</div>
