<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Newsletter\Block\Subscribe $block */

?>
<div class="block newsletter">
    <div class="title"><strong><?= $block->escapeHtml(__('Newsletter')) ?></strong></div>
    <div class="content">
        <form class="form subscribe"
            novalidate
            action="<?= $block->escapeUrl($block->getFormActionUrl()) ?>"
            method="post"
            data-mage-init='{"validation": {"errorClass": "mage-error"}}'
            id="newsletter-validate-detail">

            <div class="form-group newsletter">
                <div class="field newsletter">
                    <label class="label" for="newsletter"><span><?= $block->escapeHtml(__('Sign Up for Our Newsletter:')) ?></span></label>
                    <div class="control">
                        <input name="email" type="email" id="newsletter"
                               placeholder="<?= $block->escapeHtml(__('Enter your email address')) ?>"
                               data-validate="{required:true, 'validate-email':true}"/>
                    </div>
                </div>
                <div class="actions">
                    <button class="action subscribe primary" title="<?= $block->escapeHtmlAttr(__('Subscribe')) ?>" type="submit">
                        <span><?= $block->escapeHtml(__('Subscribe')) ?></span>
                    </button>
                </div>
            </div>

<!--            ADRIANO checkbox-->
            <div class="form-group checkbox">
                <input type="checkbox" name="conditions" id="conditions" class="conditions"
                           data-validate="{required:true}"/>
                <label for="conditions">
                    <span>
                        <?= $block->escapeHtml(__('I accept the ')) ?>
                        <a href="/aviso-legal"><?= $block->escapeHtml(__('General Conditions')) ?></a>
                        <?= $block->escapeHtml(__(' and the ')) ?>
                        <a href="/politica-de-privacidad"><?= $block->escapeHtml(__('Privacy Policy')) ?></a>
                    </span>
                </label>
            </div>
        </form>
    </div>
</div>
