<!DOCTYPE html>
<html>
<head>
    <title>Temporarily Offline</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <style>
        body {
            text-align: center;
            background-color: #004F6E
        }

        img {
            position: absolute;
            top: 50%;
            left: 50%;
            width: 552px;
            height: 350px;
            margin-top: -175px; /* Half the height */
            margin-left: -276px; /* Half the width */
        }
    </style>
</head>
<body>
    <img src="images/maintenance.jpg"/>
</body>
</html>