<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 *
 * This package designed for Magento COMMUNITY edition
 * PSS Digital does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * PSS Digital does not provide extension support in case of * incorrect edition usage.
 *
 * @author PSS Digital Team
 * @category PSS
 * @package PSS_WordPress
 * @copyright Copyright (c) 2018 PSS (https://www.pss-ti.com)
 * @license http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */
?>
<?php
/**
 * @var $block \PSS\WordPress\Block\Adminhtml\Serializer\Widget\Grid\Serializer
 */
?>
<?php $_id = 'id_' . md5(microtime()) ?>
<?php $formId = $block->getFormId()?>
<?php if (!empty($formId)) :?>
    <script>
        require([
            'prototype',
            'mage/adminhtml/grid'
        ], function(){
            Event.observe(window, "load", function(){
                var serializeInput  = document.createElement('input');
                serializeInput.type = 'hidden';
                serializeInput.name = '<?php /* @escapeNotVerified */ echo $block->getInputElementName()?>';
                serializeInput.id   = '<?php /* @escapeNotVerified */ echo $_id?>';
                try {
                    document.getElementById('<?php /* @escapeNotVerified */ echo $formId?>').appendChild(serializeInput);
                    new serializerController('<?php /* @escapeNotVerified */ echo $_id?>', <?php /* @escapeNotVerified */ echo $block->getDataAsJSON() ?>, <?php /* @escapeNotVerified */ echo $block->getColumnInputNames(true) ?>, <?php /* @escapeNotVerified */ echo $block->getGridBlock()->getJsObjectName() ?>, '<?php /* @escapeNotVerified */ echo $block->getReloadParamName()?>');
                } catch(e) {
                    //Error add serializer
                }
            });
        });
    </script>
<?php else :?>
    <input type="hidden" data-form-part="product_form" name="<?php /* @escapeNotVerified */ echo $block->getInputElementName()?>"  value="" id="<?php /* @escapeNotVerified */ echo $_id?>" />
    <script>
        require([
            'mage/adminhtml/grid'
        ], function(){
            new serializerController('<?php /* @escapeNotVerified */ echo $_id?>', <?php /* @escapeNotVerified */ echo $block->getDataAsJSON() ?>, <?php /* @escapeNotVerified */ echo $block->getColumnInputNames(true) ?>, <?php /* @escapeNotVerified */ echo $block->getGridBlock()->getJsObjectName() ?>, '<?php /* @escapeNotVerified */ echo $block->getReloadParamName()?>');
        });
    </script>
<?php endif;?>