<?php /* @var \WeltPixel\OwlCarouselSlider\Block\Slider\Products $this */ ?>

<?php $sliderData    = $this->getSliderConfiguration(); ?>
<?php $enabled       = array_key_exists('status', $sliderData) ? $sliderData['status'] : ''; ?>
<?php $showPrice     = array_key_exists('show_price', $sliderData) ? $sliderData['show_price'] : false; ?>
<?php $showAddToCart = array_key_exists('show_addto', $sliderData) ? $sliderData['show_addto'] : false; ?>
<?php $showWishlist  = (array_key_exists('show_wishlist', $sliderData) && $sliderData['show_wishlist'] !=0) ? true : false; ?>
<?php $showCompare   = (array_key_exists('show_compare', $sliderData) && $sliderData['show_compare'] !=0) ? true : false; ?>
<?php if(!$enabled){ return; } ?>
<?php
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $brand_helper = $objectManager->get('\Mageplaza\Shopbybrand\Helper\Data');
    $tax_helper   = $objectManager->get('\Magento\Catalog\Helper\Data');
    $storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
    $_helper = $this->helper('Magento\Catalog\Helper\Output');
    use Magento\Framework\App\Action\Action;
 ?>
<?php
$productsType = $this->getData('products_type');
$prCounter = 0;

if($productsType != 'recently_viewed') {
    $products = $this->getProductCollection();
    $pageSize = $products->getPageSize();
    if(!count($products)) { return; }
    $sliderConfig = json_encode($sliderData);
    $sliderTitle  = array_key_exists('title', $sliderData) ? $sliderData['title'] : '';
    $breakpoint   = $this->getBreakpointConfiguration();
    $isHoverImageEnabled = $this->isHoverImageEnabled();
    ?>
    <div class="custom-slider">
        <?php if (trim($sliderTitle)) : ?>
            <div class="content-heading">
                <h2 class="title"><?php echo $sliderTitle; ?></h2>
            </div>
        <?php endif; ?>
        <div class="owl-carousel-products-<?php echo $productsType;?> <?php echo count($products)== 1? 'owl-carousel-products-single-item': '';?>">
            <?php foreach($products as $product) : ?>

                <?php
                if ( $productsType == 'bestsell_products') {
                    $prCounter += 1;
                    if ($prCounter > $pageSize) {
                        break;
                    }
                }

                $_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
                $productImage = $_imagehelper->init($product, 'category_page_list')->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(TRUE)->resize(480, 600)->getUrl();
                $productUrl = $product->getUrlModel()->getUrl($product);
                if ($isHoverImageEnabled) {
                    $productImageHover = $_imagehelper->init($product, 'owlcarousel_product_hover')->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(TRUE)->resize(480, 600);
                    $productImageHoverUrl = $productImageHover->getUrl();
                    $productImageHoverPlaceholderUrl = $productImageHover->getDefaultPlaceholderUrl();
                }
                ?>
                <div class="item product product-item">
                    <div data-container="product-grid" class="product-item-info">
                        <?php // Discount Label ?>
                            <?php
                                $visible = '';
                                $discountPvp = 0;
                                $configdiscountPvp = [];
                                if($product->getTypeId() == \Magento\ConfigurableProduct\Model\Product\Type\Configurable::TYPE_CODE){
                                    $productTypeInstance = $product->getTypeInstance();
                                    $usedProducts = $productTypeInstance->getUsedProducts($product);
                                    foreach ($usedProducts  as $child) {
                                        $child = $objectManager->get('Magento\Catalog\Model\Product')->load($child->getId());
                                        $finalPrice = $tax_helper->getTaxPrice($child, $child->getFinalPrice(), true);
                                        $finalPrice = round($finalPrice, 2);
                                        $pvpPrice = $child->getResource()->getAttributeRawValue($child->getId(),'pvp',$storeManager->getStore()->getStoreId());
                                        if($pvpPrice && $pvpPrice > 0 && $pvpPrice > $finalPrice) {
                                            $visible = 'visible';
                                            $pvpPrice = round($pvpPrice, 2);
                                            $savePercent = (1 - ($finalPrice / $pvpPrice)) * 100;
                                            $configdiscountPvp[] = round($savePercent, 0);
                                        }
                                    }
                                    if(!empty($configdiscountPvp)){
                                        $discountPvp = max($configdiscountPvp);
                                    }
                                }else{
                                    $priceInfo = $product->getPriceInfo();
                                    $finalPrice = $priceInfo->getPrice('final_price')->getAmount()->getValue();
                                    $pvpPrice = $product->getData('pvp');
                                    $discountPvp = 0;

                                    if($pvpPrice && $pvpPrice > 0 && $pvpPrice > $finalPrice) {
                                        $visible = 'visible';
                                        $pvpPrice = round($pvpPrice, 2);
                                        $savePercent = (1 - ($finalPrice / $pvpPrice)) * 100;
                                        $discountPvp = round($savePercent, 0);
                                    }
                                }


                                if(!$discountPvp){
                                    $visible = '';
                                }
                            ?>
                            <?php if($discountPvp): ?>
                                <div class="product pvp_discount <?= /* @escapeNotVerified */ $visible; ?>">
                                    <?php if( $product->getTypeId() != 'simple' ): ?>
                                        <div class="pvp_discount_label"><?php echo __('Hasta'); ?></div>
                                    <?php endif; ?>
                                    <div class="discountPvp">-<?= /* @escapeNotVerified */  $discountPvp; ?>%</div>
                                </div>
                            <?php endif; ?>
                        <div class="product-image">
                        <a tabindex="-1" class="product photo product-item-photo" href="<?php echo $productUrl; ?>">
                            <?php
                            $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                            $registry = $objectManager->get('Magento\Framework\Registry');
                            $result = '';
                            $helperAmasty = $objectManager->get('Amasty\Label\Model\LabelViewer');
                            $result .= $helperAmasty->renderProductLabel($product, 'category');
                            $registry->register('amlabel_category_observer', true, true);

                            $registry->unregister('amlabel_current_product');
                            $registry->register('amlabel_current_product', $product);

                            //$image = 'category_page_list';
                            //$productImage = $block->getImage($product, $image);
                            ?>
                            <?php //$productImage->toHtml() ?>

                            <span style="width:240px;" class="product-image-container">
                                <span style="padding-bottom: 125%;" class="product-image-wrapper">
                                    <img width="240" height="300"
                                         alt="<?php echo $product->getName(); ?>"
                                        <?php if (!$sliderData['lazyLoad']) : ?>
                                            src="<?php echo $productImage; ?>"
                                        <?php endif; ?>
                                        <?php if ($isHoverImageEnabled && ($productImageHoverUrl != $productImageHoverPlaceholderUrl)) : ?>
                                            data-hoversrc="<?php /* @escapeNotVerified */ echo $productImageHoverUrl; ?>"
                                            onmouseover="this.setAttribute('data-tmp', this.src);this.src=this.getAttribute('data-hoversrc');"
                                            onmouseout="this.src=this.getAttribute('data-tmp')"
                                            onmousemove="if (this.getAttribute('data-hoversrc') != this.src) this.setAttribute('data-tmp', this.src)"
                                        <?php endif; ?>
                                         class="product-image-photo <?php echo $sliderData['lazyLoad'] ? 'owl-lazy' : '' ?>"
                                        <?php echo $sliderData['lazyLoad'] ? 'data-src="' . $productImage . '" data-src-retina="' . $productImage . '"' : '' ?>
                                    />
                                </span>
                            </span>
                            <?php echo $result; ?>

                        </a>
                        <div class="actions-secondary" data-role="add-to-links">
                            <?php if ($showWishlist || $showCompare): ?>
                                <div class="secondary-addto-links actions-secondary" data-role="add-to-links">

                                    <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
                                        <a href="#" data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($product); ?>'  class="action towishlist" data-action="add-to-wishlist" title="<?php /* @escapeNotVerified */ echo __('Add to Wish List') ?>">
                                            <span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
                                        </a>
                                    <?php endif; ?>

                                    <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                                        <?php
                                        $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
                                        ?>
                                        <a href="#" class="action tocompare"
                                           data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($product);?>'
                                           data-role="add-to-links"
                                           title="<?php /* @escapeNotVerified */ echo __('Add to Compare'); ?>">
                                            <span><?php /* @escapeNotVerified */ echo __('Add to Compare') ?></span>
                                        </a>
                                    <?php endif; ?>
                                </div>
                            <?php endif; ?>
                        </div>
                        </div>
                        <div class="product details product-item-details">
                            <div class="product-title-wrapper">
                                <?php $brand_name = $product->getResource()->getAttribute('manufacturer')->getFrontend()->getValue($product); ?>
                                <?php $brand_url = $brand_helper->getCustomBrandUrl($brand_name); ?>
                                <?php $brand_name = str_replace("&#039;","'",$brand_name); ?>
                                <h2 class="product-item-manufacturer">
                                    <a class="product-item-link"
                                       href="<?= /* @escapeNotVerified */ $brand_url; ?>">
                                        <?= /* @escapeNotVerified */ $product->getResource()->getAttribute('manufacturer')->getFrontend()->getValue($product); ?>
                                    </a>
                                </h2>
                                <?php $gama = $product->getData('gama'); ?>
                                <?php if($gama): ?>
                                    <div class="product gama-attribute product-gama-attr-val">
                                        <a class="product-item-link"
                                           href="<?= /* @escapeNotVerified */ $product->getProductUrl() ?>">
                                            <?= /* @escapeNotVerified */ $gama ?>
                                        </a>
                                    </div>
                                <?php endif; ?>
                                <?php if($attributeVolume = $product->getResource()->getAttribute('volumen')): ?>
                                    <?php $volumen = $attributeVolume->getFrontend()->getValue($product); ?>
                                    <div class="product description product-item-description">
                                        <span class="product_short_description"><?= /* @escapeNotVerified */ $_helper->productAttribute($product, $product->getShortDescription(), 'short_description') ?><?php if($volumen){ echo '<span class="product_volume"> '.$volumen.'</span>'; } ?></span>
                                    </div>
                                <?php endif; ?>
                            </div>

                            <?php if($showPrice) : ?>
                                <?php /* @escapeNotVerified */ echo $this->getProductPrice($product); ?>
                            <?php endif; ?>
                            <div class="product-item-inner">
                                <div class="product actions product-item-actions">
                                    <?php if($showAddToCart) : ?>
                                        <div class="actions-primary">
                                            <?php if ($product->isSaleable()): ?>
                                                <?php if ($product->getTypeInstance()->hasRequiredOptions($product)): ?>
                                                    <button class="action tocart primary" data-mage-init='{"redirectUrl": {"url": "<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($product) ?>"}}' type="button" title="<?php /* @escapeNotVerified */ echo __('View More') ?>">
                                                        <span><?php /* @escapeNotVerified */ echo __('View More') ?></span>
                                                    </button>
                                                <?php else: ?>
                                                    <?php $postParams = $block->getAddToCartPostParams($product); ?>
                                                    <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
                                                        <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                                                        <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                                        <?php echo $block->getBlockHtml('formkey')?>
                                                        <button type="submit"
                                                                title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                                class="action tocart primary">
                                                            <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                        </button>
                                                    </form>
                                                <?php endif; ?>
                                            <?php else: ?>
                                                <?php if ($product->getIsSalable()): ?>
                                                    <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                                <?php else: ?>
                                                    <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        </div>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            <?php unset($configdiscountPvp);  ?>
            <?php endforeach; ?>
        </div>
        <div id="pre-div">
            <div class="cssload-loader">
                <div class="cssload-inner cssload-one"></div>
                <div class="cssload-inner cssload-two"></div>
                <div class="cssload-inner cssload-three"></div>
            </div>
        </div>
    </div>


    <script>
        require(['jquery', 'owl_carousel', 'owl_config', 'owl_config' ],
            function ($) {
                $(document).ready(function(){

                    /*$(".product-image-photo").removeClass("lazy");
                    $(".product-image-photo").addClass("owl-lazy");*/

                    var products_type = '<?php echo $productsType;?>',
                        slider_config = <?php echo $sliderConfig; ?>,
                        carouselElement = $('.owl-carousel-products-' + products_type),
                        items = ((slider_config.items >= 0 && slider_config.items != null) ? slider_config.items : 2),
                        stagePadding = slider_config.stagePadding != '' ? parseInt(slider_config.stagePadding) : 0,
                        sPBrk_1 = slider_config.stagePadding_brk1 != '' ? parseInt(slider_config.stagePadding_brk1) : 0,
                        sPBrk_2 = slider_config.stagePadding_brk2 != '' ? parseInt(slider_config.stagePadding_brk2) : 0,
                        sPBrk_3 = slider_config.stagePadding_brk3 != '' ? parseInt(slider_config.stagePadding_brk3) : 0,
                        sPBrk_4 = slider_config.stagePadding_brk4 != '' ? parseInt(slider_config.stagePadding_brk4) : 0;
                            options = {
                                nav                 :parseInt(slider_config.nav) == 1 ? true : false,
                                dots                :parseInt(slider_config.dots) == 1 ? true : false,
                                center              :parseInt(slider_config.center) == 1 ? true : false,
                                items               :items,
                                loop                :parseInt(slider_config.loop) == 1 ? true : false,
                                margin              :parseInt(slider_config.margin) || 0,
                                stagePadding        :parseInt(slider_config.center) == 1 ? 0 : stagePadding,
                                lazyLoad            :parseInt(slider_config.lazyLoad) == 1 ? true : false,
                                autoplay            :parseInt(slider_config.autoplay) == 1 ? true : false,
                                autoplayTimeout     :(slider_config.autoplayTimeout > 0 && slider_config.autoplayTimeout != null) ? parseInt(slider_config.autoplayTimeout) : 3000,
                                autoplayHoverPause  :parseInt(slider_config.autoplayHoverPause) == 1 ? true : false,
                                autoHeight          :false,
                                responsive:{
                            <?php echo $breakpoint['breakpoint_1']; ?>:{
                                nav             :parseInt(slider_config.nav_brk1) == 1 ? true : false,
                                dots            :parseInt(slider_config.dots_brk1) == 1 ? true : false,
                                items           :(slider_config.items_brk1  >= 0 && slider_config.items_brk1 != null) ? parseInt(slider_config.items_brk1) : items,
                                center          :parseInt(slider_config.center_brk1) == 1 ? true : false,
                                stagePadding    :parseInt(slider_config.center) == 1 ? 0 : sPBrk_1
                            },
                            <?php echo $breakpoint['breakpoint_2']; ?>:{
                                nav             :parseInt(slider_config.nav_brk2) == 1 ? true : false,
                                dots            :parseInt(slider_config.dots_brk2) == 1 ? true : false,
                                items           :(slider_config.items_brk2  >= 0 && slider_config.items_brk2 != null) ? parseInt(slider_config.items_brk2) : items,
                                center          :parseInt(slider_config.center_brk2) == 1 ? true : false,
                                stagePadding    :parseInt(slider_config.center) == 1 ? 0 : sPBrk_2
                            },
                            <?php echo $breakpoint['breakpoint_3']; ?>:{
                                nav             :parseInt(slider_config.nav_brk3) == 1 ? true : false,
                                dots            :parseInt(slider_config.dots_brk3) == 1 ? true : false,
                                items           :(slider_config.items_brk3  >= 0 && slider_config.items_brk3 != null) ? parseInt(slider_config.items_brk3) : items,
                                center          :parseInt(slider_config.center_brk3) == 1 ? true : false,
                                stagePadding    :parseInt(slider_config.center) == 1 ? 0 : sPBrk_3
                            },
                            <?php echo $breakpoint['breakpoint_4']; ?>:{
                                nav             :parseInt(slider_config.nav_brk4) == 1 ? true : false,
                                dots            :parseInt(slider_config.dots_brk4) == 1 ? true : false,
                                items           :(slider_config.items_brk4  >= 0 && slider_config.items_brk4 != null) ? parseInt(slider_config.items_brk4) : items,
                                center          :parseInt(slider_config.center_brk4) == 1 ? true : false,
                                stagePadding    :parseInt(slider_config.center) == 1 ? 0 : sPBrk_4,

                            }
                        }
                    };

                    // workaround for owl carousel
                    // fix nav buttons display on load even when set as false
                    carouselElement.on('initialized.owl.carousel', function(event) {
                        setTimeout(function(){
                            carouselElement.trigger('next.owl.carousel');
                        }, 370);
                    });
                    /** Lazyload bug when fewer items exist in the carousel then the ones displayed */
                    carouselElement.on('initialized.owl.carousel', function(event){
                        var scopeSize = event.page.size;
                        for (var i = 0; i < scopeSize; i++){
                            var imgsrc = $(event.target).find('.owl-item').eq(i).find('img').attr('data-src');
                            $(event.target).find('.owl-item').eq(i).find('img').attr('src', imgsrc);
                            $(event.target).find('.owl-item').eq(i).find('img').attr('style', 'opacity: 1;');
                        }
                    });
                    carouselElement.owlCarousel(options);
                });
            });
    </script>
    <script type="text/javascript">
            require(['jquery'],function($){
                $(document).ready(function(){
                    setTimeout(function(){
                        if(jQuery(".amasty-label-container").length > 0){
                            $(".amasty-label-container").parents(".product-item").addClass('label-exist');
                        }
                    }, 2000);
                });
            });
        </script>
<?php
} else {
?>
    <div id="recently_viewed"></div>

    <script type="text/x-magento-init">
    {
        "#recently_viewed": {
            "owlAjax": {
                "ajaxUrl": "<?php echo $block->getUrl('ajaxowl/recentlyviewed/index') ?>",
                "requestType": "recently_viewed"
            }
        }

    }
    </script>
<?php
}
?>


