<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer */

$_item = $block->getItem();

$product = $_item->getProduct();
$isVisibleProduct = $product->isVisibleInSiteVisibility();
/** @var \Magento\Msrp\Helper\Data $helper */
$helper = $this->helper('Magento\Msrp\Helper\Data');
$canApplyMsrp = $helper->isShowBeforeOrderConfirm($product) && $helper->isMinimalPriceLessMsrp($product);
/** @var \Alfa9\GiftProduct\Helper\Data $helperGiftProduct */
$helperGiftProduct = $this->helper('Alfa9\GiftProduct\Helper\Data');
/** @var  \Magento\Framework\Pricing\Helper\Data $helperPrice */
$helperPrice = $this->helper('Magento\Framework\Pricing\Helper\Data');
//$_item->getBaseCalculationPrice() + $_item->getTaxAmount();
?>
<tbody class="cart item">
<tr class="item-info">
    <td data-th="<?= $block->escapeHtml(__('Item')) ?>" class="col item">
        <?php if ($block->hasProductUrl()): ?>
        <a href="<?= /* @escapeNotVerified */$block->getProductUrl() ?>"
           title="<?= $block->escapeHtml($block->getProductName()) ?>"
           tabindex="-1"
           class="product-item-photo">
            <?php else: ?>
            <span class="product-item-photo">
            <?php endif; ?>
            <?= $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml() ?>
            <?php if ($block->hasProductUrl()): ?>
        </a>
    <?php else: ?>
        </span>
    <?php endif; ?>
        <div class="product-item-details">
            <h2 class="product-item-manufacturer"><?php echo $product->getResource()->getAttribute('manufacturer')->getFrontend()->getValue($product); ?></h2>
            <strong class="product-item-name">
                <?php if ($block->hasProductUrl()): ?>
                    <a href="<?= /* @escapeNotVerified */
                    $block->getProductUrl() ?>"><?= $block->escapeHtml($block->getProductName()) ?></a>
                <?php else: ?>
                    <?= $block->escapeHtml($block->getProductName()) ?>
                <?php endif; ?>
            </strong>
            <div class="product-item-description">
                <?php echo $_item->getProduct()->getData('short_description'); ?>
            </div>
            <?php if ($_options = $block->getOptionList()): ?>
                <dl class="item-options">
                    <?php foreach ($_options as $_option) : ?>
                        <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                        <dt><?= $block->escapeHtml($_option['label']) ?></dt>
                        <dd>
                            <?php if (isset($_formatedOptionValue['full_view'])): ?>
                                <?= /* @escapeNotVerified */
                                $_formatedOptionValue['full_view'] ?>
                            <?php else: ?>
                                <?= /* @escapeNotVerified */
                                $_formatedOptionValue['value'] ?>
                            <?php endif; ?>
                        </dd>
                    <?php endforeach; ?>
                </dl>
            <?php endif; ?>
            <?php if ($messages = $block->getMessages()): ?>
                <?php foreach ($messages as $message): ?>
                    <div class="cart item message <?= /* @escapeNotVerified */
                    $message['type'] ?>">
                        <div><?= $block->escapeHtml($message['text']) ?></div>
                    </div>
                <?php endforeach; ?>
            <?php endif; ?>
            <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
            <?php if ($addInfoBlock): ?>
                <?= $addInfoBlock->setItem($_item)->toHtml() ?>
            <?php endif; ?>
        </div>
        <div class="field qty">
            <label class="label" for="cart-<?= /* @escapeNotVerified */
            $_item->getId() ?>-qty">
                    <span><?= /* @escapeNotVerified */
                        __('Qty') ?></span>
            </label>
            <div class="control qty">
                <input id="cart-<?= /* @escapeNotVerified */
                $_item->getId() ?>-qty"
                       name="cart[<?= /* @escapeNotVerified */
                       $_item->getId() ?>][qty]"
                       data-cart-item-id="<?= $block->escapeHtml($_item->getSku()) ?>"
                       value="<?= /* @escapeNotVerified */
                       $block->getQty() ?>"
                       type="number"
                       size="4"
                       title="<?= $block->escapeHtml(__('Qty')) ?>"
                       class="input-text qty"
                       data-validate="{required:true,'validate-greater-than-zero':true}"
                       data-role="cart-item-qty"/>
                <div class="qty_control">
                    <button type="button" id="<?= /* @escapeNotVerified */
                    $_item->getId() ?>-dec" class="decreaseQty"><span><?= $block->escapeHtml(__('-')) ?></button>
                    <button type="button" id="<?= /* @escapeNotVerified */
                    $_item->getId() ?>-upt" class="increaseQty"><span><?= $block->escapeHtml(__('+')) ?></button>
                </div>
            </div>
        </div>
    </td>
    <td class="col subtotal" data-th="<?= $block->escapeHtml(__('Subtotal')) ?>">
        <div class="actions-toolbar visible-xs hidden-xl">
            <?= /* @escapeNotVerified */
            $block->getActions($_item) ?>
        </div>
        <?php if ($canApplyMsrp): ?>
            <span class="cart msrp subtotal">--</span>
        <?php else: ?>
            <?= $block->getRowTotalHtml($_item) ?>
        <?php endif; ?>
    </td>

    <td class="col item-actions-custom visible-xl hidden-xs" data-th="<?= $block->escapeHtml(__('Actions')) ?>">
        <div class="actions-toolbar">
            <div class="field gift-product-action">
                <label id="<?= /* @escapeNotVerified */
                $_item->getId() ?>-custom-gift" class="label gift-link" for="cart-<?= /* @escapeNotVerified */
                $_item->getId() ?>-is-gift">
                    <span><?= /* @escapeNotVerified */
                        __('Is Gift?') ?></span>
                    <span><?= /* @escapeNotVerified */
                        __('Additional Price: %1',
                            $helperPrice->currency(number_format($helperGiftProduct->getProductPriceGift(), 2), true, false)); ?></span>
                </label>
                <div class="control is-gift">
                    <input type="checkbox"
                           id="cart-<?= /* @escapeNotVerified */
                           $_item->getId() ?>-is-gift"
                           name="cart[<?= /* @escapeNotVerified */
                           $_item->getId() ?>][is_gift]"
                        <?php echo $_item->getData('is_gift') ? 'checked' : ''; ?>/>
                </div>
            </div>
            <?= /* @escapeNotVerified */$block->getActions($_item) ?>
        </div>
    </td>
</tr>

</tbody>
<script type="text/javascript">
    require(["jquery"], function ($) {
        $('#<?php echo $_item->getId();?>-upt, #<?php echo $_item->getId();?>-dec').on(" click ", function () {
            var $this = $(this);
            var selectField = $(".control.qty").find('#cart-<?php echo $_item->getId();?>-qty');
            var currentQty = selectField.val();
            if ($this.hasClass('increaseQty')) {
                var newAdd = parseInt(currentQty) + parseInt(1);
                selectField.val(newAdd)
            } else {
                if (currentQty > 1) {
                    var newAdd = parseInt(currentQty) - parseInt(1);
                    selectField.val(newAdd)
                }
            }
        });
    });
</script>

<script type="text/javascript">
    require(['jquery', 'jquery/ui'], function ($) {
        $('#<?php echo $_item->getId();?>-custom-gift').on('click', function () {
            var $this = $(this);
            if ($this.hasClass('gift-link-red')){
                console.log('remove');
                $this.removeClass('gift-link-red');
            } else {
                console.log('add');
                $this.addClass('gift-link-red');
            }
        });
    });
</script>