<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Magento\Catalog\Block\Product\AbstractProduct */
?>

<?php
/* @var WeltPixel\OwlCarouselSlider\Helper\Products $helper */
$helper = $this->helper('WeltPixel\OwlCarouselSlider\Helper\Products');
$sliderConfiguration = $helper->getSliderConfiguration($block->getType());
$sliderConfig = json_encode($sliderConfiguration);
$helperCustom = $this->helper('WeltPixel\OwlCarouselSlider\Helper\Custom');
$breakpointConfiguration = $helperCustom->getBreakpointConfiguration();
$displaySocial = $helperCustom->getDisplaySocial();
$breakpoint   = $breakpointConfiguration;
$enableSlider = (array_key_exists('status', $sliderConfiguration) && $sliderConfiguration['status'] == 1) ? true : false ;
$imageCreationOptions = [];
if ($enableSlider) {
    $imageCreationOptions['weltpixel_owlcarousel'] = true;
    if ($sliderConfiguration['lazyLoad']) {
        $imageCreationOptions['weltpixel_lazyLoad'] = true;
    }
}

/** WeltPixel_GoogleTagManager */
$currentProduct = $this->getProduct();
$listValue = '';
$gtmHelper = $this->helper('WeltPixel\GoogleTagManager\Helper\Data');
?>
<?php
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $brand_helper = $objectManager->get('\Mageplaza\Shopbybrand\Helper\Data');
 ?>
<?php

switch ($type = $block->getType()) {

    case 'related-rule':
        if ($exist = $block->hasItems()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = ($sliderConfiguration['title']) ? $sliderConfiguration['title'] : __('Related Products');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showWishlist = $displaySocial['display_wishlist'];
            $showCompare = $displaySocial['display_compare'];
            $showAddTo = true;
            $showCart = false;
            $templateType = null;
            $description = false;
            $listValue = $currentProduct->getName() . ' ' . __('Related Products');
        }
        break;

    case 'related':
        /** @var \Magento\Catalog\Block\Product\ProductList\Related $block */
        if ($exist = $block->getItems()->getSize()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = ($sliderConfiguration['title']) ? $sliderConfiguration['title'] : __('Related Products');
            $items = $block->getItems();
            $limit = 0;
            $shuffle = 0;
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showWishlist = $displaySocial['display_wishlist'];
            $showCompare = $displaySocial['display_compare'];
            $showAddTo = true;
            $showCart = false;
            $templateType = null;
            $description = false;
            $listValue = $currentProduct->getName() . ' ' . __('Related Products');
        }
        break;

    case 'upsell-rule':
        if ($exist = $block->hasItems()) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = ($sliderConfiguration['title']) ? $sliderConfiguration['title'] : __('We found other products you might like!');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();

            $showWishlist = $displaySocial['display_wishlist'];
            $showCompare = $displaySocial['display_compare'];
            $showAddTo = false;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
            $listValue = $currentProduct->getName() . ' ' . __('Upsell Products');
        }
        break;

    case 'upsell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Upsell $block */
        if ($exist = count($block->getItemCollection()->getItems())) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = ($sliderConfiguration['title']) ? $sliderConfiguration['title'] : __('We found other products you might like!');
            $items = $block->getItemCollection()->getItems();
            $limit = $block->getItemLimit('upsell');
            $shuffle = 0;

            $showWishlist = $displaySocial['display_wishlist'];
            $showCompare = $displaySocial['display_compare'];
            $showAddTo = false;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
            $listValue = $currentProduct->getName() . ' ' . __('Upsell Products');
        }
        break;

    case 'crosssell-rule':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->hasItems()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = ($sliderConfiguration['title']) ? $sliderConfiguration['title'] : __('More Choices:');
            $items = $block->getItemCollection();

            $showWishlist = $displaySocial['display_wishlist'];
            $showCompare = $displaySocial['display_compare'];
            $showAddTo = false;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
            $listValue = __('Crossel Products');
        }
        break;

    case 'crosssell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->getItemCount()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = ($sliderConfiguration['title']) ? $sliderConfiguration['title'] : __('More Choices:');
            $items = $block->getItems();

            $showWishlist = $displaySocial['display_wishlist'];
            $showCompare = $displaySocial['display_compare'];
            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
            $listValue = __('Crossel Products');
        }
        break;

    case 'new':
        if ($exist = $block->getProductCollection()) {
            $type = 'new';
            $mode = 'grid';
            $type = $type . ' ' . $mode;

            $class = 'widget' . ' ' . $type;

            $image = 'new_products_content_widget_grid';
            $title = ($sliderConfiguration['title']) ? $sliderConfiguration['title'] : __('New Products');
            $items = $exist;

            $showWishlist = $displaySocial['display_wishlist'];
            $showCompare = $displaySocial['display_compare'];
            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = ($mode == 'list') ? true : false;
            $canItemsAddToCart = false;
            $listValue = __('New Products');
        }
        break;

    case 'other':
        break;
}
?>

<?php if ($exist):?>

    <?php if($enableSlider) : ?>
    <script>
        require(['jquery', 'owl_carousel', 'owl_config' ],
            function ($) {
				 $(document).ready(function(){
                var products_type = '<?php echo $type;?>',
                    slider_config = <?php echo $sliderConfig; ?>,

                    carouselElement = $('.owl-carousel-products-' + products_type),

	                windowWidth = $(window).width(),
	                carouselWidth = carouselElement.width(),
	                carouselContainer = carouselWidth + 120,

                    items = ((slider_config.items >= 0 && slider_config.items != null) ? slider_config.items : 2),

	                stagePadding = slider_config.stagePadding != '' ? parseInt(slider_config.stagePadding) : 0,

	                sPBrk_1 = slider_config.stagePadding_brk1 != '' ? parseInt(slider_config.stagePadding_brk1) : 0,
	                sPBrk_2 = slider_config.stagePadding_brk2 != '' ? parseInt(slider_config.stagePadding_brk2) : 0,
	                sPBrk_3 = slider_config.stagePadding_brk3 != '' ? parseInt(slider_config.stagePadding_brk3) : 0,
	                sPBrk_4 = slider_config.stagePadding_brk4 != '' ? parseInt(slider_config.stagePadding_brk4) : 0;

	            options = {
	                nav                 :parseInt(slider_config.nav) == 1 ? true : false,
	                dots                :parseInt(slider_config.dots) == 1 ? true : false,
	                center              :parseInt(slider_config.center) == 1 ? true : false,
	                items               :items,
	                loop                :parseInt(slider_config.loop) == 1 ? true : false,
	                margin              :parseInt(slider_config.margin) != '' && slider_config.margin != null ? parseInt(slider_config.margin) : 0,
	                stagePadding        :parseInt(slider_config.center) == 1 ? 0 : stagePadding,
	                lazyLoad            :parseInt(slider_config.lazyLoad) == 1 ? true : false,
	                autoplay            :parseInt(slider_config.autoplay) == 1 ? true : false,
	                autoplayTimeout     :(slider_config.autoplayTimeout > 0 && slider_config.autoplayTimeout != null) ? parseInt(slider_config.autoplayTimeout) : 3000,
	                autoplayHoverPause  :parseInt(slider_config.autoplayHoverPause) == 1 ? true : false,
	                autoHeight          :false,


	                responsive:{
	                    <?php echo $breakpoint['breakpoint_1']; ?>:{
	                        nav             :parseInt(slider_config.nav_brk1) == 1 ? true : false,
	                        dots            :parseInt(slider_config.dots_brk1) == 1 ? true : false,
	                        items           :(slider_config.items_brk1  >= 0 && slider_config.items_brk1 != null) ? parseInt(slider_config.items_brk1) : items,
	                        center          :parseInt(slider_config.center_brk1) == 1 ? true : false,
	                        stagePadding    :parseInt(slider_config.center) == 1 ? 0 : sPBrk_1,
	                    },
	                   <?php echo $breakpoint['breakpoint_2']; ?>:{
	                        nav             :parseInt(slider_config.nav_brk2) == 1 ? true : false,
	                        dots            :parseInt(slider_config.dots_brk2) == 1 ? true : false,
	                        items           :(slider_config.items_brk2  >= 0 && slider_config.items_brk2 != null) ? parseInt(slider_config.items_brk2) : items,
	                        center          :parseInt(slider_config.center_brk2) == 1 ? true : false,
	                        stagePadding    :parseInt(slider_config.center) == 1 ? 0 : sPBrk_2,
	                    },
	                    <?php echo $breakpoint['breakpoint_3']; ?>:{
	                        nav             :parseInt(slider_config.nav_brk3) == 1 ? true : false,
	                        dots            :parseInt(slider_config.dots_brk3) == 1 ? true : false,
	                        items           :(slider_config.items_brk3  >= 0 && slider_config.items_brk3 != null) ? parseInt(slider_config.items_brk3) : items,
	                        center          :parseInt(slider_config.center_brk3) == 1 ? true : false,
	                        stagePadding    :parseInt(slider_config.center) == 1 ? 0 : sPBrk_3,
	                    },
	                    <?php echo $breakpoint['breakpoint_3']; ?>:{
	                        nav             :parseInt(slider_config.nav_brk4) == 1 ? true : false,
	                        dots            :parseInt(slider_config.dots_brk4) == 1 ? true : false,
	                        items           :(slider_config.items_brk4  >= 0 && slider_config.items_brk4 != null) ? parseInt(slider_config.items_brk4) : items,
	                        center          :parseInt(slider_config.center_brk4) == 1 ? true : false,
	                        stagePadding    :parseInt(slider_config.center) == 1 ? 0 : sPBrk_4,
	                    }
	                }
					
					
	            };
				
				// workaround for owl carousel
				// track window for owl breakpoint
				$(window).on('resize', (function (){
					
					var ww = $( window ).width();
					
					var sResp1 = <?php echo $breakpoint['breakpoint_1']; ?>;
					var sResp2 = <?php echo $breakpoint['breakpoint_2']; ?>;
					var sResp3 = <?php echo $breakpoint['breakpoint_3']; ?>;
					var sResp4 = <?php echo $breakpoint['breakpoint_4']; ?>;
					
					var navBtnL = carouselElement.find('.owl-prev');
					var navBtnR = carouselElement.find('.owl-next');
					if((ww >= sResp4 && slider_config.nav_brk4 != 1)
						|| (ww >= sResp3 && ww < sResp4 && slider_config.nav_brk3 != 1)
						|| (ww >= sResp2 && ww < sResp3 && slider_config.nav_brk2 != 1)
						|| (ww >= sResp1 && ww < sResp2 && slider_config.nav_brk1 != 1)
					){
						navBtnL.css('display', 'none');
						navBtnR.css('display', 'none');
					}
				}));

                 /** Lazyload bug when fewer items exist in the carousel then the ones displayed */
                carouselElement.on('initialized.owl.carousel', function(event){
                    var scopeSize = event.page.size;
                    for (var i = 0; i < scopeSize; i++){
                        var imgsrc = $(event.target).find('.owl-item').eq(i).find('img').attr('data-src');
                        $(event.target).find('.owl-item').eq(i).find('img').attr('src', imgsrc);
                        $(event.target).find('.owl-item').eq(i).find('img').attr('style', 'opacity: 1;');
                    }
                });
				
				// fix nav buttons display on load even when set as false
				setTimeout(function(){
				 $(window).trigger('resize');
				}, 100);
				carouselElement.owlCarousel(options);

                var carouselControls = carouselElement.find('.owl-nav');

	            if (carouselContainer >= windowWidth) {

	                carouselControls.find('.owl-prev').css({
	                    'left': 0,
	                    'top': -15
	                });
	                carouselControls.find('.owl-next').css({
	                    'right': 0,
	                    'top': -15
	                });
	            }

			});
		});
    </script>
    <?php endif;?>
<?php if ($type == 'related' || $type == 'upsell'): ?>
<?php if ($type == 'related'): ?>
<div class="section-related block-margin block <?php /* @escapeNotVerified */ echo $class . !$enableSlider ? ' row' : ''; ?> hidden-xs" data-mage-init='{"relatedProducts":{"relatedCheckbox":".related.checkbox"}}' data-limit="<?php /* @escapeNotVerified */ echo $limit; ?>" data-shuffle="<?php /* @escapeNotVerified */ echo $shuffle; ?>">
    <?php else: ?>
    <div class="block-margin block <?php /* @escapeNotVerified */ echo $class . !$enableSlider ? ' row' : ''; ?> hidden-xs" data-mage-init='{"upsellProducts":{}}' data-limit="<?php /* @escapeNotVerified */ echo $limit; ?>" data-shuffle="<?php /* @escapeNotVerified */ echo $shuffle; ?>">
        <?php endif; ?>
        <?php else: ?>
        <div class="block <?php /* @escapeNotVerified */ echo $class; ?>">
            <?php endif; ?>
            <h3 class="block-title title">
                <span id="block-<?php /* @escapeNotVerified */ echo $class?>-heading" role="heading" aria-level="2"><?php /* @escapeNotVerified */ echo $title; ?></span>
            </h3>
            <div class="block-content content" aria-labelledby="block-<?php /* @escapeNotVerified */ echo $class?>-heading">
                <?php if ($type == 'related' && $canItemsAddToCart): ?>
                    <div class="block-actions">
                        <?php /* @escapeNotVerified */ echo __('Check items to add to the cart or') ?>
                        <button type="button" class="action select" role="select-all"><span><?php /* @escapeNotVerified */ echo __('select all') ?></span></button>
                    </div>
                <?php endif; ?>
                <div class="products wrapper grid products-grid products-<?php /* @escapeNotVerified */ echo $type; ?>">
                    <ol class="products list items product-items<?php echo $enableSlider ? ' owl-carousel-products-' . $type : ''; ?>">
                        <?php $product_item = $enableSlider ? '' : ' product-item'; ?>
                        <?php $iterator = 1; ?>
                        <?php foreach ($items as $_item): ?>
                            <?php $available = ''; ?>
                            <?php if (!$_item->isComposite() && $_item->isSaleable() && $type == 'related'): ?>
                                <?php if (!$_item->getRequiredOptions()): ?>
                                    <?php $available = 'related-available'; ?>
                                <?php endif; ?>
                            <?php endif; ?>

                            <?php if ($type == 'related' || $type == 'upsell'): ?>
                                <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item" style="">' : '</li><li class="item product product-item" style="">' ?>
                            <?php else: ?>
                                <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                            <?php endif; ?>

                            <div class="product-item-info <?php /* @escapeNotVerified */ echo $available; ?>">
                                <?php /* @escapeNotVerified */ echo '<!-- ' . $image . '-->' ?>
                                <a <?php if ($gtmHelper->isProductClickTrackingEnabled()) :
                                        echo $this->helper('WeltPixel\GoogleTagManager\Helper\Data')->addProductClick($_item, $iterator-1, $listValue);
                                    endif; ?>
                                        href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" class="product photo product-item-photo">
                                        <?php echo $block->getImage($_item, $image, $imageCreationOptions)->toHtml(); ?>
                                    </a>
                                <div class="product details product-item-details">
                                    <div class="product-title-wrapper">
                                        <h2 class="product-item-manufacturer">
                                            <?php $brand_name = $_item->getResource()->getAttribute('manufacturer')->getFrontend()->getValue($_item); ?>
                                            <?php $brand_url = $brand_helper->getCustomBrandUrl($brand_name); ?>
                                            <?php $brand_name = str_replace("&#039;","'",$brand_name); ?>
                                            <a class="product-item-link"
                                               href="<?php /* @escapeNotVerified */ echo $brand_url; ?>">
                                                <?= /* @escapeNotVerified */ $_item->getResource()->getAttribute('manufacturer')->getFrontend()->getValue($_item); ?>
                                            </a>
                                        </h2>
                                        <?php 
                                            $productName = $_item->getName();
                                            if($brand_name){ 
                                                $productName = str_ireplace($brand_name,"",$productName);
                                            }
                                        ?>
                                        <strong class="product name product-item-name">
                                            <a class="product-item-link" title="<?php echo $block->escapeHtml($productName) ?>" href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>">
                                                <?php echo $block->escapeHtml($productName) ?>
                                            </a>
                                        </strong>
                                    </div>

                                <?php /* @escapeNotVerified */ echo $block->getProductPrice($_item); ?>

                                <?php if ($templateType): ?>
                                    <?php echo $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                <?php endif; ?>

                                <?php if (!$_item->isComposite() && $_item->isSaleable() && $type == 'related'): ?>
                                    <?php if (!$_item->getRequiredOptions()): ?>
                                        <div class="product-item-inner">
                                            <div class="product actions product-item-actions aaaaaaaaaa">
                                                <div class="actions-primary">
                                                    <?php /*<button class="action tocart primary" type="button" title="<?php /* @escapeNotVerified */ /*echo __('Buy') ?>" onclick="location.href='<?= /* @escapeNotVerified */ /*$_item->getProductUrl() ?>'">
                                                        <span><?php /* @escapeNotVerified */ /*echo __('Buy') ?></span>
                                                    </button> */?>

                                                    <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                                        <button class="action tocart primary" data-mage-init='{"redirectUrl": {"url": "<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($_item) ?>"}}' type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                            <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                        </button>
                                                    <?php else: ?>
                                                        <?php $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                        $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                                        ?>
                                                        <button class="action tocart primary"
                                                                data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
                                                                type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                            <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                        </button>
                                                    <?php endif; ?>


                                                </div>
                                            </div>
                                        </div>
                                    <?php endif; ?>
                                <?php endif; ?>

                                <?php if ($showWishlist || $showCompare || $showCart): ?>
                                    <div class="product actions product-item-actions ssssssssss">
                                        <?php if ($showCart): ?>
                                            <div class="actions-primary">
                                                <?php if ($_item->isSaleable()): ?>
                                                    <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                                        <button class="action tocart primary" data-mage-init='{"redirectUrl": {"url": "<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($_item) ?>"}}' type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                            <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                        </button>
                                                    <?php else: ?>
                                                        <?php $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                        $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                                        ?>
                                                        <button class="action tocart primary"
                                                                data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
                                                                type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                            <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                        </button>
                                                    <?php endif; ?>
                                                <?php else: ?>
                                                    <?php if ($_item->getIsSalable()): ?>
                                                        <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                                    <?php else: ?>
                                                        <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                            </div>
                                        <?php endif; ?>

                                            <?php if ($showWishlist || $showCompare): ?>
                                                <div class="secondary-addto-links actions-secondary" data-role="add-to-links">
                                                    <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
                                                        <a href="#" data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_item); ?>'  class="action towishlist" data-action="add-to-wishlist" title="<?php /* @escapeNotVerified */ echo __('Add to Wish List') ?>">
                                                            <span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
                                                        </a>
                                                    <?php endif; ?>
                                                    <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                                                        <?php
                                                        $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
                                                        ?>
                                                        <a href="#" class="action tocompare"
                                                           data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_item);?>'
                                                           data-role="add-to-links"
                                                           title="<?php /* @escapeNotVerified */ echo __('Add to Compare'); ?>">
                                                            <span><?php /* @escapeNotVerified */ echo __('Add to Compare') ?></span>
                                                        </a>
                                                    <?php endif; ?>
                                                </div>
                                            <?php endif; ?>
                                        </div>
                                    <?php endif; ?>
                                </div>
                            </div>
                            <?php echo($iterator == count($items)+1) ? '</li>' : '' ?>
                        <?php endforeach ?>
                    </ol>
                    <?php if($enableSlider) : ?>
					<div id="pre-div">
						<div class="cssload-loader">
							<div class="cssload-inner cssload-one"></div>
							<div class="cssload-inner cssload-two"></div>
							<div class="cssload-inner cssload-three"></div>
						</div>
					</div>
					<?php endif; ?>
                </div>
            </div>
        </div>
        <?php endif;?>



    <?php if ($exist): ?>
    <?php if ($type == 'related' || $type == 'upsell'): ?>
    <?php if ($type == 'related'): ?>
    <div class="section-related block <?= /* @escapeNotVerified */
    $class ?> visible-xs" data-mage-init='{"relatedProducts":{"relatedCheckbox":".related.checkbox"}}'
         data-limit="<?= /* @escapeNotVerified */
         $limit ?>" data-shuffle="<?= /* @escapeNotVerified */
    $shuffle ?>">
        <?php else: ?>
        <div class="section-related block <?= /* @escapeNotVerified */
        $class ?> visible-xs " data-mage-init='{"upsellProducts":{}}' data-limit="<?= /* @escapeNotVerified */
        $limit ?>" data-shuffle="<?= /* @escapeNotVerified */
        $shuffle ?>">
            <?php endif; ?>
            <?php else: ?>
            <div class="block <?= /* @escapeNotVerified */
            $class ?>">
                <?php endif; ?>
                <div class="block-title title">
                    <strong id="block-<?= /* @escapeNotVerified */
                    $class ?>-heading" role="heading" aria-level="2"><?= /* @escapeNotVerified */
                        $title ?></strong>
                </div>
                <div class="block-content content" aria-labelledby="block-<?= /* @escapeNotVerified */
                $class ?>-heading">
                    <?php if ($type == 'related' && $canItemsAddToCart): ?>
                        <div class="block-actions">
                            <?= /* @escapeNotVerified */
                            __('Check items to add to the cart or') ?>
                            <button type="button" class="action select" role="select-all">
                        <span><?= /* @escapeNotVerified */
                            __('select all') ?></span></button>
                        </div>
                    <?php endif; ?>
                    <?php foreach ($items as $_item): ?>
                        <?php $available = '';

                        ?>
                        <?php if (!$_item->isComposite() && $_item->isSaleable() && $type == 'related'): ?>
                            <?php if (!$_item->getRequiredOptions()): ?>
                                <?php $available = 'related-available'; ?>
                            <?php endif; ?>
                        <?php endif;
                        $_item['data_available'] = $available
                        ?>
                        <?php if ($type == 'related' || $type == 'upsell'): ?>
                            <?php $_item['data_li'] = '<li class="item product product-item" style="">' ?>
                        <?php else: ?>
                            <?php $_item['data_li'] = '<li class="item product product-item">' ?>
                        <?php endif; ?>
                        <?php $_item['data_image'] = $image ?>
                        <?php $_item['data_getProductUrl'] = $block->getProductUrl($_item) ?>
                        <?php $_item['data_getImageHtml'] = $block->getImage($_item, $image, $imageCreationOptions)->toHtml();?>
                        <?php $_item['data_escapeHtml'] = $block->escapeHtml($_item->getName()) ?>
                        <?php $_item['data_getProductUrl'] = $block->getProductUrl($_item) ?>
                        <?php $_item['data_manufacturer'] = $_item->getResource()->getAttribute('manufacturer')->getFrontend()->getValue($_item) ?>
                        <?php $_item['data_getProductPrice'] = $block->getProductPrice($_item) ?>
                        <?php $_item['data_getReviewsSummaryHtml'] = '' ?>
                        <?php if ($templateType): ?>
                            <?php $_item['data_getReviewsSummaryHtml'] = $block->getReviewsSummaryHtml($_item, $templateType) ?>
                        <?php endif; ?>
                        <?php $_item['data_requiredOptionsHtml'] = '' ?>
                        <?php if ($canItemsAddToCart && !$_item->isComposite() && $_item->isSaleable() && $type == 'related'): ?>
                            <?php if (!$_item->getRequiredOptions()): ?>
                                <?php $_item['data_requiredOptionsHtml'] = '
                                <div class="product-item-inner">
                                    <div class="product actions product-item-actions">
                                        <div class="actions-primary" style="width: 100%; display:block">
                                            <button class="action tocart primary" type="button" title="'.__('Buy').'" onclick="location.href=\''.$_item->getProductUrl() .'\'"
                                            style ="width: 100%">
                                                <span>'.__('Buy').'</span>
                                            </button>
                                        </div>
                                    </div>
                                </div>
                                '
                                ?>
                            <?php endif; ?>
                        <?php endif; ?>
                        <?php $_item['data_ifShowAddToOrShowCart'] = $showAddTo || $showCart ?>
                        <?php if ($showAddTo || $showCart): ?>
                            <?php $_item['data_ifShowCart'] = $showCart ?>
                            <?php if ($showCart): ?>
                                <?php $_item['data_isSaleable'] = $_item->isSaleable() ?>
                                <?php if ($_item->isSaleable()): ?>
                                    <?php $_item['data_hasRequiredOptions'] = $_item->getTypeInstance()->hasRequiredOptions($_item) ?>
                                    <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                        <?php $_item['data_button'] = '<button class="action tocart primary" 
                                                        data-mage-init=\'{"redirectUrl": {"url": "' . $block->getAddToCartUrl($_item) . '"}}\' 
                                                        type="button" 
                                                        title="' . __('Add to Cart') . '">
                                                    <span>' . __('Add to Cart') . '</span>
                                                </button>' ?>
                                    <?php else: ?>
                                        <?php $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                        $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                        ?>
                                        <?php $_item['data_button'] = '<button class="action tocart primary"
                                                        data-post="' . $postData . '"
                                                        type="button" title="' . __('Add to Cart') . '">
                                                    <span>' . __('Add to Cart') . '</span>
                                                </button>' ?>
                                    <?php endif; ?>
                                <?php else: ?>
                                    <?php $_item['data_getIsSalable'] = $_item->getIsSalable() ?>
                                    <?php if ($_item->getIsSalable()): ?>
                                        <?php $_item['data_inStockDiv'] = '<div class="stock available"><span>' . __('In stock') . '</span></div>' ?>
                                    <?php else: ?>
                                        <?php $_item['data_outOfStockDiv'] = '<div class="stock unavailable"><span>' . __('Out of stock') . '</span></div>' ?>
                                    <?php endif; ?>
                                <?php endif; ?>
                            <?php endif; ?>
                            <?php $_item['data_ifShowAddTo'] = $showAddTo ?>
                            <?php if ($showAddTo): ?>
                                <?php $_item['data_showAddToDiv'] = '<div class="secondary-addto-links actions-secondary" data-role="add-to-links">' ?>
                                <?php $_item['data_ifShowAddTo'] = $block->getChildBlock('addto') ?>
                                <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                    <?php $_item['data_addToBlockHtml'] = $addToBlock->setProduct($_item)->getChildHtml() ?>
                                <?php endif; ?>
                            <?php endif; ?>
                        <?php endif; ?>
                    <?php endforeach ?>
                    <div id="cardss"></div>
                </div>
                <div id="pagination"></div>
            </div>

            <script type="text/javascript">
                window['_arr'] = <?php echo json_encode($items->toArray()); ?>;
                window['arr'] = [];
                for(var key in window['_arr']) {
                    window['arr'].push(window['_arr'][key]);
                }
                window['totalRelated'] = window['arr'].length;
                window['builList'] = function (_array, indexPage) {
                    var count = 0 ;
                    var init = '<div class="products wrapper grid products-grid products-<?= /* @escapeNotVerified */ $type ?>">\n' +
                        '                            <ol class="products list items product-items">';
                    var result = init;

                    for(var item of _array) {
                        count++;
                        var showFavorites = '';
                        if(item['data_ifShowAddToOrShowCart']) {
                            showFavorites += '  <div class="product actions product-item-actions">\n';
                            if(item['data_ifShowAddTo']) {
                                showFavorites += item['data_showAddToDiv'];
                                if(item['data_ifShowAddTo']) {
                                    showFavorites += item['data_addToBlockHtml'];
                                }
                                showFavorites += '            </div>\n';
                            }
                            if(item['data_ifShowCart']) {
                                showFavorites += '  <div class="actions-primary">\n';
                                if(item['data_isSaleable']) {
                                    showFavorites += item['data_button'];
                                } else {
                                    if(item['data_getIsSalable']) {
                                        showFavorites += item['data_inStockDiv'];
                                    } else {
                                        showFavorites += item['data_outOfStockDiv'];
                                    }
                                }
                                showFavorites += '             </div>\n';
                            }
                            showFavorites += '            </div>\n';
                        }


                        result +=item['data_li'] ;
                        result +='    <div class="product-item-info '+item['data_available']+'">' ;
                        result +=showFavorites;
                        result +='        <a href="'+item['data_getProductUrl']+'" class="product photo product-item-photo">' ;
                        result +=item['data_getImageHtml'].replace('data-src','src');
                        result +='        </a>' ;
                        result +='        <div class="product details product-item-details">' ;
                        result +='           <div class="product-title-wrapper">' ;
                        result +='             <h2 class="product-item-manufacturer" style="text-align: center">' ;
                        result +='                 <a class="product-item-link"';
                        result +='                    href="'+item['data_getProductUrl']+'">' ;
                        result +=item['data_manufacturer'];
                        result +='                 </a>' ;
                        result +='             </h2>' ;
                        result +='            <strong class="product name product-item-name">' ;
                        result +='                <a class="product-item-link" title="'+item['data_escapeHtml']+'" href="'+item['data_getProductUrl']+'"' ;
                        result +='>'+item['data_escapeHtml']+'</a>' ;
                        result +='            </strong>' ;
                        result +='         </div>' ;
                        result +=item['data_getProductPrice'];
                        result +=item['data_getReviewsSummaryHtml'];
                        result +=item['data_requiredOptionsHtml'];
                        result += '        </div>\n' +
                            '    </div>\n' +
                            '</li>';
                        if(count == 2){
                            result += '</ol>' + init;
                        }
                    };
                    result += '</ol>' +
                        '</div>';
                    result += '';
                    document.getElementById("cardss").innerHTML = result;
                    window['buildPagination'](indexPage,4,window['totalRelated']);
                };

                window['buildPagination'] = function(indexPage, size, total) {
                    var totalPages = Math.trunc(total / size);
                    if (total % size != 0){totalPages ++}
                    var previous = '';
                    if(indexPage > 1) {
                        previous = '<li class="item pages-item-previous">\n' +
                            '                            <a class="action  previous" href="javascript:void(0);"  onclick="window[\'builList\'](window[\'arr\'].slice('+((size * (indexPage-1)) - size)+','+ (size * (indexPage-1))+'),'+(indexPage-1)+');" title="Previous">\n' +
                            '                                <span class="label">Page</span>\n' +
                            '                                <span>Previous</span>\n' +
                            '                            </a>\n' +
                            '                        </li>';
                    }
                    var next = '';
                    if(indexPage < totalPages) {
                        next = '<li class="item pages-item-next">\n' +
                            '                            <a class="action  next" href="javascript:void(0);"  onclick="window[\'builList\'](window[\'arr\'].slice('+((size * (indexPage+1)) - size)+','+ (size * (indexPage+1))+'),'+(indexPage+1)+');" title="Previous">\n' +
                            '                                <span class="label">Page</span>\n' +
                            '                                <span>Next</span>\n' +
                            '                            </a>\n' +
                            '                        </li>';
                    }
                    var items = '';
                    var position = 0;
                    for(var i = 1; i <= totalPages; i++) {
                        if(+i == +indexPage) {
                            items += '<li class="item">\n' +
                                ' <strong class="page">' +
                                '<span class="label">Youre currently reading page</span>'+
                            '<span>'+i+'</span>'+
                            '</strong>' +
                                '                        </li>';
                        } else {
                            items += '<li class="item">\n' +
                                '                            <a href="javascript:void(0);" onclick="window[\'builList\'](window[\'arr\'].slice(' + position + ',' + (position + size) + '),' + i + ');" class="page">\n' +
                                '                                <span class="label">Page</span>\n' +
                                '                                <span>' + i + '</span>\n' +
                                '                            </a>\n' +
                                '                        </li>';
                        }
                        position += size;
                    }
                    document.getElementById("pagination").innerHTML = '<div class="pages">\n' +
                        '                    <strong class="label pages-label" id="paging-label">Page</strong>\n' +
                        '                    <ul class="items pages-items" aria-labelledby="paging-label">' +
                        previous + items + next +
                        ' </ul>\n' +
                        '                </div>';
                };
                window.onload = function () {
                    window['builList'](window['arr'].slice(0,4), 1);
                };

            </script>
            <?php endif;?>

