<!--
/**
* NOTA SOBRE LA LICENCIA DE USO DEL SOFTWARE
* 
* El uso de este software está sujeto a las Condiciones de uso de software que
* se incluyen en el paquete en el documento "Aviso Legal.pdf". También puede
* obtener una copia en la siguiente url:
* http://www.redsys.es/wps/portal/redsys/publica/areadeserviciosweb/descargaDeDocumentacionYEjecutables
* 
* Redsys es titular de todos los derechos de propiedad intelectual e industrial
* del software.
* 
* Quedan expresamente prohibidas la reproducción, la distribución y la
* comunicación pública, incluida su modalidad de puesta a disposición con fines
* distintos a los descritos en las Condiciones de uso.
* 
* Redsys se reserva la posibilidad de ejercer las acciones legales que le
* correspondan para hacer valer sus derechos frente a cualquier infracción de
* los derechos de propiedad intelectual y/o industrial.
* 
* Redsys Servicios de Procesamiento, S.L., CIF B85955367
*/
-->

<?php
    switch ($this->getExito()) {
        case 0:
            //echo __("Gracias por confiar en nosotros. El pago del pedido ha sido procesado con éxito.")."<br/>";
            $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
            $_helper = $objectManager->get('WeltPixel\ThankYouPage\Helper\Data');
            $pageSubtitle = $_helper->getPageSubTitle();
            ?>
        <div class="thankyou-wrapper">
            <div class="inner-wrapper-thankyou">
                <div class="checkout-page-title-wrapper thank-you-page">
                    <div class="icon_thank_you_01"><img alt="<?= /* @escapeNotVerified */ __('Thank you') ?>" src="<?php echo $block->getViewFileUrl('images/thankyoupage/check.png') ?>"></div>
                </div>
                <div class="checkout-success">
                    <span class="title-order"><?= __('Your order has been successfully completed.'); ?></span>
                    <h1 class="page-title"><?= $_helper->getPageTitle() ?></h1>
                    
                    <?php if ($block->getOrderId()):?>
                        <?php if ($block->getCanViewOrder()) :?>
                            <p class="order-number"><?= __($pageSubtitle, sprintf('<a href="%s" class="order-number"><strong>%s</strong></a>', $block->escapeHtml($block->getViewOrderUrl()), $block->escapeHtml($block->getOrderId()))) ?></p>
                        <?php  else :?>
                            <p><?= __($pageSubtitle, sprintf('<strong>%s</strong>', $block->escapeHtml($block->getOrderId()))) ?></p>
                        <?php endif;?>
                            <p><?= $_helper->getOrderDescription() ?></p>
                    <?php endif;?>

                    <?= $block->getAdditionalInfoHtml() ?>

                    <?php if ($_helper->showContinueShopping()) : ?>
                    <div class="actions-toolbar">
                        <div class="primary continue-shipping">
                            <a class="action primary continue" href="<?= /* @escapeNotVerified */ $block->getContinueUrl() ?>"><span><?= /* @escapeNotVerified */ __('Continue Shopping') ?></span></a>
                        </div>
                        <div class="primary print-receipt">
                            <?php if ($block->getCanViewOrder() && $block->getCanPrintOrder()) :?>
                                <a href="<?= /* @escapeNotVerified */ $block->getPrintUrl() ?>" target="_blank" class="print">
                                    <?= /* @escapeNotVerified */ __('Print receipt') ?>
                                </a>
                                <?= $block->getChildHtml() ?>
                            <?php endif;?>
                        </div>
                    </div>
                    <?php else: ?>
                    <div class="actions-toolbar">
                        <div class="primary">
                            <?php if ($block->getCanViewOrder() && $block->getCanPrintOrder()) :?>
                                <a href="<?= /* @escapeNotVerified */ $block->getPrintUrl() ?>" target="_blank" class="print">
                                    <?= /* @escapeNotVerified */ __('Print receipt') ?>
                                </a>
                                <?= $block->getChildHtml() ?>
                            <?php endif;?>
                        </div>
                    </div>
                    <?php endif; ?>
                </div>
            </div>
        </div>
            <?php

                    
                    
                    
                    
                 
                    
			break;
		case 1:
			echo "<b>". __("La forma en que intenta acceder al sistema de notificacion no es correcta.")."</b><br/>";
			echo __("Este mensaje lo puede estar viendo por dos motivos:")."<br/><br/>";
			echo "<ol>";
				echo "<li>".__("El hosting del comercio utiliza redirección internamente.")."</li>";
				echo "<li>".__("Está usted intentando navegar por esta página; esta pagina no está accesible para entrar directamente desde el navegador de internet.")."</li>";
			echo "</ol>";
			echo __("Si ha llegado aquí redirigido desde la pasarela de pago, contacte con el soporte del comercio.");
			break;
		case 2:
			echo __("Gracias por confiar en nosotros. Se ha producido un error durante el pago.")."<br/>";			
			echo __("Si el problema persiste contacte con el soporte del comercio.");
			break;
		case 3:
			echo __("Gracias por confiar en nosotros. Se ha producido un error durante el pago.")."<br/>";
			echo __("Si el problema persiste contacte con el soporte del comercio.");
			break;
		case 4:
			echo __("Se ha producido un error desconocido");
			echo __("Por favor, contacte con el soporte del comercio");
			break;
					
	}


