<?php
/** @var \Algolia\AlgoliaSearch\Block\Algolia $block */

$config = $block->getConfigHelper();

$catalogSearchHelper = $block->getCatalogSearchHelper();

$placeholder = __('Search for products, categories, ...');
/** Render form with autocomplete input **/
if ($config->isDefaultSelector()) : ?>
    <a href="#" class="search-mobile-icon" id="search-mobile-icon">
        <span><?= __("Search"); ?></span>
    </a>
    <div class="block block-search algolia-search-block" id="algolia-searchbox-content">
        <a class="closebutton icon-line-cross" id="close-search-mobile-icon">
        </a>
        <div class="block block-title"><strong><?php echo $block->escapeHtml(__('Search')); ?></strong></div>
        <div class="block block-content">
            <form id="search_mini_form"
                  action="<?php echo $block->escapeHtml($catalogSearchHelper->getResultUrl()); ?>"
                  method="get">
                <div id="algolia-searchbox">
                    <label for="search"><?php echo $block->escapeHtml(__('Search:')); ?></label>

                    <input id="search"
                           type="text"
                           name="<?php echo $block->escapeHtml($catalogSearchHelper->getQueryParamName()); ?>"
                           class="input-text algolia-search-input"
                           autocomplete="off"
                           spellcheck="false"
                           autocorrect="off"
                           autocapitalize="off"
                           placeholder="<?php echo $block->escapeHtml($placeholder); ?>" />

                    <span class="clear-cross clear-query-autocomplete"></span>
                    <span id="algolia-glass" class="magnifying-glass" width="24" height="24"></span>
                </div>
            </form>
        </div>
    </div>
<?php endif; ?>
<script type="application/javascript">
    require(['jquery', 'jquery/ui'], function($){
        $('#search-mobile-icon').click(function () {
            var searchBlock = $('#algolia-searchbox-content');
            if(searchBlock.length > 0 && !searchBlock.hasClass('open')){
                searchBlock.addClass('open');
            }
        });
        $('#close-search-mobile-icon').click(function () {
            var searchBlock = $('#algolia-searchbox-content');
            if(searchBlock.length > 0 && searchBlock.hasClass('open')){
                searchBlock.removeClass('open');
            }
        });
    });
</script>
